[package]
name = "mew-collab"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.0", features = ["napi4"] }
napi-derive = "3.6.2"
yrs = "0.27.3"

[build-dependencies]
napi-build = "2.4.0"

[profile.release]
lto = true
strip = true
