import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowUpRight, Check, CheckCircle, Copy, Download, Folder, InfoCircle, Play, RefreshDouble, Settings as SettingsIcon, Terminal, Pause, SunLight, HalfMoon, WarningTriangle, Computer, CloudDownload, Eye, EyeClosed, Xmark } from 'iconoir-react'
import * as bridge from './bridge'
import { canRetryUpdate, canUpdate, defaultSettings, stageNames, stateOf, type Action, type Credential, type Log, type Page, type Settings, type Snapshot, type Update } from './model'
function MewMark({ className = '' }: { className?: string }) { return <svg className={className} width="34" height="34" viewBox="0 0 64 64" fill="none" aria-hidden="true"><rect x="2" y="2" width="60" height="60" stroke="currentColor" strokeWidth="4"/><path d="M46 29.75C46 18.5 46 14 39 14C32 14 32 18.5 32 29.75C32 18.5 32 14 25 14C18 14 18 18.5 18 29.75L21.5 32L18 34.25C18.0002 45.5 18 50 25 50C32 50 32 45.5 32 34.25C32 45.5 32 50 39 50C46 50 46 45.5 46 34.25" stroke="currentColor" strokeWidth="4"/></svg> }

const pages: { id: Page; label: string; icon: typeof Computer }[] = [{ id: 'overview', label: '개요', icon: Computer }, { id: 'environment', label: '환경과 설치', icon: Terminal }, { id: 'updates', label: '업데이트', icon: CloudDownload }, { id: 'logs', label: '작업 로그', icon: InfoCircle }, { id: 'settings', label: '설정', icon: SettingsIcon }]
const actionLabels: Record<string, string> = { install: 'mew 설치', start: '서버 시작', stop: '서버 중지', restart: '서버 재시작', update: '업데이트', 'check-update': '업데이트 확인', 'update-wsl': 'WSL 업데이트', 'desktop-setup': '원격 데스크톱 준비' }
const time = (value: number) => new Date(value).toLocaleTimeString('ko-KR', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' })
function Pill({ text, tone = 'neutral' }: { text: string; tone?: string }) { return <span className={`pill ${tone}`}><span className="dot" />{text}</span> }
function Value({ children }: { children?: React.ReactNode }) { return <span className="value">{children || '아직 확인되지 않음'}</span> }
function Fact({ label, children }: { label: string; children?: React.ReactNode }) { return <div className="fact"><dt>{label}</dt><dd><Value>{children}</Value></dd></div> }
function IconButton({ label, children, onClick, disabled }: { label: string; children: React.ReactNode; onClick: () => void; disabled?: boolean }) { return <button className="icon-button" type="button" aria-label={label} title={label} onClick={onClick} disabled={disabled}>{children}</button> }

export function App() {
  const [page, setPage] = useState<Page>('overview'), [snapshot, setSnapshot] = useState<Snapshot | null>(null)
  const [settings, setSettings] = useState<Settings>({ ...defaultSettings }), [draft, setDraft] = useState<Settings>({ ...defaultSettings })
  const [saving, setSaving] = useState(false)
  const [busy, setBusy] = useState<Action | null>(null), [stage, setStage] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [rows, setRows] = useState<Log[]>([]), [update, setUpdate] = useState<Update | null>(null), [credential, setCredential] = useState<Credential | null>(null), [reveal, setReveal] = useState(false)
  const [filter, setFilter] = useState('all'), [theme, setTheme] = useState(() => localStorage.getItem('mew-manager-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'))
  const pending = useRef(false), savingRef = useRef(false), alive = useRef(true), logEnd = useRef<HTMLDivElement>(null)
  const status = stateOf(snapshot), linux = snapshot?.linux, system = snapshot?.system
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('mew-manager-theme', theme) }, [theme])
  const perform = useCallback(async (action: Action) => {
    if (pending.current) return
    pending.current = true; setBusy(action); if (action !== 'inspect') { setError(''); setNotice(''); setStage('') }
    try {
      const next = await bridge.run(action)
      if (alive.current && next) setSnapshot(next)
      if (alive.current && action !== 'inspect') { setNotice(next?.system.rebootRequired ? 'Windows를 재부팅하면 설치를 이어서 진행할 수 있습니다.' : `${actionLabels[action]} 작업을 마쳤습니다.`); if (action === 'install' || action === 'update') setUpdate(null) }
    } catch (cause) {
      if (alive.current) setError(cause instanceof Error ? cause.message : String(cause))
      if (action !== 'inspect') { try { const next = await bridge.run('inspect'); if (alive.current && next) setSnapshot(next) } catch { } }
    }
    finally { pending.current = false; if (alive.current) setBusy(null) }
  }, [])
  useEffect(() => {
    alive.current = true
    let stop: (() => void) | undefined
    void (async () => {
      try {
        stop = await bridge.events({ log: row => setRows(old => [...old.slice(-599), row]), stage: setStage, credential: value => { setCredential(value); setReveal(false) }, update: setUpdate, notice: setNotice })
        if (!alive.current) { stop(); return }
        const [config, history] = await Promise.all([bridge.settings(), bridge.logs()])
        if (!alive.current) return
        setSettings(config); setDraft(config); setRows(history)
        await perform('inspect')
      } catch (cause) { if (alive.current) setError(String(cause)) }
    })()
    const timer = setInterval(() => { if (bridge.native && !pending.current) void perform('inspect') }, 30_000)
    return () => { alive.current = false; stop?.(); clearInterval(timer) }
  }, [perform])
  useEffect(() => { if (page === 'logs') logEnd.current?.scrollIntoView({ block: 'nearest' }) }, [rows, page])
  const save = async () => {
    if (pending.current || savingRef.current) return null
    savingRef.current = true; setSaving(true)
    try { const saved = await bridge.saveSettings(draft); setSettings(saved); setDraft(saved); setNotice('설정을 저장했습니다.'); setError(''); return saved }
    catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); return null }
    finally { savingRef.current = false; setSaving(false) }
  }
  const install = async () => {
    if (!draft.ownerEmail.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)) { setError('첫 관리자 계정의 이메일을 입력하세요.'); setPage('settings'); return }
    if (await save()) await perform('install')
  }
  const invokeAction = (action: Action) => { if (action === 'install') void install(); else void perform(action) }
  const copyText = async (text: string) => { try { await navigator.clipboard.writeText(text); setNotice('복사했습니다.') } catch { setError('클립보드에 복사하지 못했습니다. 텍스트를 직접 선택해 복사하세요.') } }
  const logs = filter === 'error' ? rows.filter(row => row.kind === 'error') : rows
  const installed = Boolean(linux?.installed), controlsDisabled = Boolean(busy) || saving || !bridge.native
  const last = rows.filter(row => row.kind === 'stage' || row.kind === 'error').slice(-3).reverse()
  const installedInput = Boolean(system?.distroInstalled && system.managed)
  const readiness = [
    { title: 'Windows & WSL 2', detail: system?.wslInstalled ? `WSL 준비됨 · ${system.os}` : system ? 'WSL 2를 준비합니다' : 'Windows 환경 확인', ready: Boolean(system?.wslInstalled) },
    { title: `${settings.distro} · Ubuntu`, detail: system?.distroInstalled ? (system.managed ? '전용 Linux 환경 준비됨' : '같은 이름의 기존 환경 확인 필요') : '나만의 독립된 Linux 환경', ready: Boolean(system?.distroInstalled && system.managed) },
    { title: 'mew', detail: installed ? `${linux?.branch || '브랜치 확인 중'} · ${linux?.commit || '버전 확인 중'}` : '앱 설치와 관리자 계정 준비', ready: Boolean(installed && linux?.built) },
    { title: '로컬 서버', detail: snapshot?.httpOk ? `localhost:${linux?.port}` : '브라우저에서 연결 확인', ready: Boolean(snapshot?.httpOk) },
  ]
  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="#overview" onClick={e => { e.preventDefault(); setPage('overview') }}><MewMark /><span>mew<span className="brand-suffix">Manager</span></span></a>
      <div className="host-label"><span className="dot" />Windows workspace</div>
      <nav aria-label="관리 메뉴">{pages.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={`nav-item ${page === id ? 'active' : ''}`} aria-current={page === id ? 'page' : undefined} onClick={() => setPage(id)}><Icon width={19} height={19} /><span>{label}</span>{id === 'updates' && update && update.behind > 0 && <span className="nav-count">{update.behind}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="server-mini"><span className={`dot ${snapshot?.httpOk ? 'success' : ''}`} /><span>{snapshot?.httpOk ? '로컬 서버 실행 중' : '로컬 환경 관리'}<small>{settings.distro} · WSL 2</small></span></div><div className="sidebar-footer"><span>v0.1.1 · Portable</span><IconButton label={theme === 'dark' ? '라이트 테마' : '다크 테마'} onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <SunLight width={17} height={17} /> : <HalfMoon width={17} height={17} />}</IconButton></div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><div><span className="breadcrumb">mew Manager</span><span className="slash">/</span><span>{pages.find(p => p.id === page)?.label}</span></div><div className="top-actions"><Pill text={status.label} tone={status.tone} /><IconButton label="상태 새로고침" onClick={() => void perform('inspect')} disabled={Boolean(busy)}><RefreshDouble className={busy === 'inspect' ? 'spinning' : ''} width={18} height={18} /></IconButton></div></header>
      <main>
        {!bridge.native && <div className="preview-notice"><InfoCircle width={17} height={17} /><span>브라우저 미리보기입니다. 설치·서버 조작은 Windows 실행 파일에서 사용할 수 있습니다.</span></div>}
        {error && <div role="alert" className="message error"><WarningTriangle width={18} height={18} /><span>{error}</span><IconButton label="오류 닫기" onClick={() => setError('')}><Xmark width={16} height={16} /></IconButton></div>}
        {notice && <div role="status" className="message"><CheckCircle width={17} height={17} /><span>{notice}</span><IconButton label="알림 닫기" onClick={() => setNotice('')}><Xmark width={16} height={16} /></IconButton></div>}
        {credential && <section className="credential" aria-label="첫 관리자 계정"><div className="section-heading"><h2>첫 로그인 정보</h2><IconButton label="로그인 정보 닫기" onClick={() => { setCredential(null); setReveal(false) }}><Xmark width={17} height={17} /></IconButton></div><p>이 정보는 로그나 설정에 저장되지 않습니다. 첫 로그인에서 비밀번호를 변경하세요.</p><dl><Fact label="이메일">{credential.email}</Fact><div className="credential-password"><span>임시 비밀번호</span><code>{reveal ? credential.password : '••••••••••••'}</code><IconButton label={reveal ? '비밀번호 숨기기' : '비밀번호 보기'} onClick={() => setReveal(!reveal)}>{reveal ? <EyeClosed width={17} height={17} /> : <Eye width={17} height={17} />}</IconButton><IconButton label="임시 비밀번호 복사" onClick={() => void copyText(credential.password)}><Copy width={17} height={17} /></IconButton></div></dl></section>}
        {busy && busy !== 'inspect' && <section className="operation" aria-label="진행 중인 작업"><div><span className="operation-spinner" /><strong role="status" aria-live="polite" aria-atomic="true">{stageNames[stage] || actionLabels[busy]}</strong><button type="button" className="text-button" onClick={() => setPage('logs')}>진행 로그 보기<ArrowUpRight width={15} height={15} /></button></div><div className="indeterminate" /><p>창을 열어 두세요. 실패하면 현재 환경을 확인하고 다시 이어서 진행할 수 있습니다.</p></section>}
        {page === 'overview' && <>
          <section className="welcome"><div><h1>{status.title.split('\n').map((line, index) => <span key={index}>{line}</span>)}</h1><p>{system?.rebootRequired ? 'Windows를 재부팅한 뒤 이 앱을 다시 열고 설치를 이어서 진행하세요.' : installed ? '문서, 코드, 터미널과 에이전트. 익숙한 브라우저에서 이어가세요.' : 'WSL 준비부터 서버 실행까지. 터미널을 열지 않고 한곳에서 관리하세요.'}</p><div className="welcome-actions">{status.action === 'open' ? <button className="primary" disabled={controlsDisabled} onClick={() => void bridge.openMew(linux?.port || settings.port).catch(e => setError(String(e)))}>mew 열기<ArrowUpRight width={18} height={18} /></button> : status.action && <button className="primary" disabled={controlsDisabled} onClick={() => invokeAction(status.action as Action)}>{status.action === 'install' ? '설치 시작' : actionLabels[status.action]}{status.action === 'install' ? <Download width={18} height={18} /> : <Play width={18} height={18} />}</button>}<button className="secondary" onClick={() => setPage(installed ? 'environment' : 'settings')}>{installed ? '환경 자세히 보기' : '설치 설정'}<ArrowUpRight width={16} height={16} /></button></div></div><div className="workspace-mark" aria-hidden="true"><MewMark /></div></section>
          <section className="readiness" aria-label="설치 단계">{readiness.map((item, i) => <div className={`readiness-step ${item.ready ? 'done' : ''}`} key={item.title}><div className="step-track"><span className="step-dot">{item.ready ? <Check width={15} height={15} /> : i + 1}</span>{i < readiness.length - 1 && <span className="step-line" />}</div><strong>{item.title}</strong><small>{item.detail}</small></div>)}</section>
          <div className="overview-bottom"><section className="panel"><div className="section-heading"><h2>서버</h2><Pill text={snapshot?.httpOk ? '연결 가능' : linux?.running ? '응답 확인 필요' : '중지됨'} tone={snapshot?.httpOk ? 'success' : 'neutral'} /></div><dl><Fact label="접속 주소"><code>http://localhost:{linux?.port || settings.port}</code></Fact><Fact label="작업 폴더"><code>{linux?.workspace || settings.workspace}</code></Fact><Fact label="실행 환경">{settings.distro} / Ubuntu / WSL 2</Fact></dl><div className="panel-actions"><button className="secondary" disabled={controlsDisabled || !installed || Boolean(linux?.running)} onClick={() => invokeAction('start')}><Play width={16} height={16} />시작</button><button className="secondary" disabled={controlsDisabled || !linux?.running} onClick={() => invokeAction('stop')}><Pause width={16} height={16} />중지</button><IconButton label="서버 재시작" disabled={controlsDisabled || !installed} onClick={() => invokeAction('restart')}><RefreshDouble width={17} height={17} /></IconButton></div></section><section className="activity"><div className="section-heading"><h2>최근 활동</h2><button className="text-button" onClick={() => setPage('logs')}>전체 로그<ArrowUpRight width={15} height={15} /></button></div>{last.length ? last.map((row, i) => <div className="activity-row" key={i}><span className={`dot ${row.kind === 'error' ? 'danger' : 'accent'}`} /><div><span>{row.kind === 'stage' ? stageNames[row.text.replace('단계: ', '')] || row.text : row.text}</span><small>{time(row.time)}</small></div></div>) : <div className="empty-activity"><Terminal width={25} height={25} /><p>설치·실행 기록이 여기에 쌓입니다.</p></div>}<div className="activity-foot"><span className="dot success" />설정과 데이터는 앱을 닫아도 유지됩니다.</div></section></div>
        </>}
        {page === 'environment' && <><div className="page-heading"><h1>환경과 설치</h1><p>Windows에서 시작하고, Linux에서 일합니다.</p></div><section className="panel"><div className="section-heading"><h2>Windows</h2><Pill text={system?.supported ? '지원 환경' : '확인 필요'} tone={system?.supported ? 'success' : 'warning'} /></div><dl><Fact label="운영체제">{system?.os}</Fact><Fact label="빌드 / CPU">{system?.build && `${system.build} / ${system.architecture}`}</Fact><Fact label="가상화">{system ? system.virtualization ? '사용 가능' : 'BIOS/UEFI 설정 확인 필요' : ''}</Fact></dl></section><section className="panel"><div className="section-heading"><h2>WSL & Ubuntu</h2><button className="secondary small" disabled={controlsDisabled || !system?.wslInstalled} onClick={() => invokeAction('update-wsl')}><RefreshDouble width={15} height={15} />WSL 업데이트</button></div><dl><Fact label="WSL 버전"><span className="multiline">{system?.wslVersion}</span></Fact><Fact label="관리 배포판">{settings.distro}{system?.distroInstalled ? ` · WSL ${system.distroVersion}${system.managed ? ' · 전용 환경' : ' · 기존 환경'}` : ' · 아직 설치되지 않음'}</Fact><Fact label="다른 배포판">{system?.distributions.filter(d => d.name !== settings.distro).map(d => `${d.name} (WSL ${d.version})`).join(', ') || '없음'}</Fact></dl></section><section className="panel"><div className="section-heading"><h2>mew & 개발 도구</h2><Pill text={installed ? '설치됨' : '설치 필요'} tone={installed ? 'success' : 'neutral'} /></div><dl><Fact label="mew 버전">{linux?.commit && `${linux.branch} · ${linux.commit}${linux.dirty ? ' · 로컬 변경 있음' : ''}`}</Fact>{['node', 'npm', 'git', 'tmux', 'python'].map(tool => <Fact label={tool === 'node' ? 'Node.js' : tool} key={tool}>{linux?.tools[tool]}</Fact>)}</dl><div className="panel-actions"><button className="secondary" disabled={controlsDisabled} onClick={() => invokeAction('install')}><Download width={16} height={16} />{installed ? '설치 복구' : '설치 시작'}</button><button className="secondary" disabled={controlsDisabled || !installed} onClick={() => invokeAction('desktop-setup')}><Computer width={16} height={16} />원격 데스크톱 준비</button></div></section></>}
        {page === 'updates' && <><div className="page-heading"><h1>업데이트</h1><p>현재 버전과 새 변경 내용을 확인하세요.</p></div><section className="update-summary"><CloudDownload width={44} height={44} /><div><h2>{update ? update.ahead ? '로컬 커밋을 확인해 주세요.' : update.behind ? `${update.behind}개의 새 커밋이 있어요.` : '최신 상태예요.' : '새 버전을 확인해 볼까요?'}</h2><p>{update ? update.ahead ? '로컬 커밋이 있어 자동 업데이트를 적용할 수 없습니다.' : linux?.dirty ? '로컬 변경을 먼저 커밋하거나 보관하세요.' : '업데이트는 내려받기·설치·빌드 후 서버를 재시작합니다.' : 'GitHub의 main 브랜치와 현재 설치를 비교합니다.'}</p></div><button className="primary" disabled={controlsDisabled || !installed} onClick={() => invokeAction('check-update')}><RefreshDouble width={16} height={16} />확인</button></section><section className="panel"><dl><Fact label="현재 설치">{linux?.commit}</Fact><Fact label="최신 버전">{update?.latest}</Fact><Fact label="로컬 변경">{linux ? linux.dirty ? '변경 있음' : '변경 없음' : ''}</Fact></dl>{update?.commits.length ? <div className="commit-list">{update.commits.map(commit => <div key={commit}><span className="dot accent" /><code>{commit.slice(0, 8)}</code><span>{commit.slice(9)}</span></div>)}</div> : null}<div className="panel-actions"><button className="primary" disabled={controlsDisabled || (!canUpdate(snapshot, update) && !canRetryUpdate(snapshot))} onClick={() => invokeAction('update')}><Download width={17} height={17} />{canRetryUpdate(snapshot) ? '업데이트 다시 시도' : '업데이트 적용'}</button></div></section><p className="support-note">Manager v0.1.1 · 관리 앱 자체는 새 실행 파일로 교체합니다. WSL과 사용자 데이터는 유지됩니다.</p></>}
        {page === 'logs' && <><div className="page-heading"><h1>작업 로그</h1><p>설치 진행과 문제 발생 지점을 확인하세요.</p></div><div className="log-toolbar"><div className="segmented" aria-label="로그 필터"><button aria-pressed={filter === 'all'} onClick={() => setFilter('all')}>전체 <span>{rows.length}</span></button><button aria-pressed={filter === 'error'} onClick={() => setFilter('error')}>오류 <span>{rows.filter(r => r.kind === 'error').length}</span></button></div><button className="secondary small" onClick={() => void copyText(logs.map(row => `${time(row.time)} ${row.text}`).join('\n'))} disabled={!logs.length}><Copy width={15} height={15} />로그 복사</button></div><div className="log-view" role="log" aria-label="작업 출력" aria-live="polite">{logs.length ? logs.map((row, index) => <div className={`log-line ${row.kind}`} key={index}><time>{time(row.time)}</time><span>{row.text}</span></div>) : <div className="log-empty"><Terminal width={32} height={32} /><strong>{filter === 'error' ? '기록된 오류가 없습니다.' : '아직 작업 기록이 없습니다.'}</strong><p>작업을 시작하면 단계와 출력이 여기에 표시됩니다.</p></div>}<div ref={logEnd} /></div></>}
        {page === 'settings' && <><div className="page-heading"><h1>설정</h1><p>mew가 머무를 환경을 준비하세요.</p></div><form className="panel settings-form" onSubmit={e => { e.preventDefault(); void save() }}><div className="section-heading"><h2>설치 환경</h2><span className="muted">현재 PC에 저장</span></div><label>WSL 배포판 이름<input value={draft.distro} onChange={e => setDraft({ ...draft, distro: e.target.value })} disabled={controlsDisabled || installedInput} maxLength={40} /></label><label>mew 설치 폴더<input value={draft.installPath} onChange={e => setDraft({ ...draft, installPath: e.target.value })} disabled={controlsDisabled || installed} /></label><label>작업 폴더<input value={draft.workspace} onChange={e => setDraft({ ...draft, workspace: e.target.value })} disabled={controlsDisabled || installed} /></label><div className="settings-row"><label>포트<input type="number" min={1024} max={65535} value={draft.port} onChange={e => setDraft({ ...draft, port: Number(e.target.value) })} disabled={controlsDisabled || installed} /></label><label>첫 관리자 이메일<input type="email" placeholder="you@example.com" value={draft.ownerEmail} onChange={e => setDraft({ ...draft, ownerEmail: e.target.value })} disabled={controlsDisabled || installed} autoComplete="email" /></label></div><div className="panel-actions"><button type="submit" className="primary" disabled={controlsDisabled}>설정 저장<Check width={16} height={16} /></button>{!installed && <button type="button" className="secondary" disabled={controlsDisabled} onClick={() => void install()}>저장하고 설치<Download width={16} height={16} /></button>}</div></form><section className="panel"><div className="section-heading"><h2>설정과 데이터</h2><button className="secondary small" disabled={!bridge.native} onClick={() => void bridge.openFolder().catch(e => setError(String(e)))}><Folder width={16} height={16} />관리 폴더 열기</button></div><dl><Fact label="관리 앱">%LOCALAPPDATA%\Mew\Manager</Fact><Fact label="mew 데이터"><code>{linux?.paths.data || '/home/mew/.local/share/mew'}</code></Fact><Fact label="서버 설정"><code>{linux?.paths.config || '/home/mew/.config/mew/config.env'}</code></Fact></dl></section><section className="appearance"><div><h2>화면 테마</h2><p>이 기기에만 적용됩니다.</p></div><div className="segmented"><button onClick={() => setTheme('light')} aria-pressed={theme === 'light'}><SunLight width={15} height={15} />라이트</button><button onClick={() => setTheme('dark')} aria-pressed={theme === 'dark'}><HalfMoon width={15} height={15} />다크</button></div></section></>}
      </main>
      <footer className="statusbar"><span><span className="dot accent" />{busy ? stageNames[stage] || (busy === 'inspect' ? '환경 상태 확인 중' : actionLabels[busy]) : '로컬에서 실행 · 데이터는 내 PC에'}</span><span>{snapshot?.checkedAt ? `${time(snapshot.checkedAt)} 확인` : '상태 확인 중'}</span></footer>
    </div>
  </div>
}
