import './test-isolated-data.ts'
import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import http from 'node:http'
import crypto from 'node:crypto'
import { execFileSync } from 'node:child_process'
import express from 'express'
import { build } from 'rolldown'
import { compile } from '@tailwindcss/node'
import { chromium } from 'playwright-core'
import { domBrowserExecutable } from './browser-dom-executable.ts'
import { FeatureStore } from './features.ts'
import { FeatureService } from './feature-service.ts'
import { createFeatureRouter } from './feature-routes.ts'
import { WORKSPACE_ROOT, setWorkspaceRoot } from './paths.ts'
import { writeSets } from './agentSets.ts'
import { setFeature } from './access-policy.ts'
import type { AgentHostCallbacks } from './agentHost.ts'

const root = path.resolve(import.meta.dirname, '..')
test('feature GUI implements compact hierarchy, editing, assignment, review, evidence and mobile navigation', { skip: !domBrowserExecutable(), timeout: 60_000 }, async () => {
  const temporary = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'mew-feature-ui-'))), workspace = path.join(temporary, 'project'), original = WORKSPACE_ROOT
  fs.mkdirSync(workspace); fs.writeFileSync(path.join(workspace, 'login.ts'), 'export const login = true')
  const git = (...args: string[]) => execFileSync('git', ['-C', workspace, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim()
  git('init', '-q'); git('add', 'login.ts'); git('-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'Add login')
  const hash = git('rev-parse', 'HEAD')
  setWorkspaceRoot(workspace)
  const store = new FeatureStore(path.join(temporary, 'state'))
  const set = { id: crypto.randomUUID(), name: '기본 구현팀', role: 'Build', runtime: 'codex', modelId: '' }
  const secondSet = { ...set, id: crypto.randomUUID(), name: '두 번째 팀' }; writeSets([set, secondSet])
  const report = { summary: '로그인을 구현했습니다.', validation: '기능 검증 통과', files: ['login.ts'], commits: [{ repository: '', hash }] }
  const make = async (title: string, status: 'verified' | 'needs-fix' | null = null) => {
    const run = await store.request(workspace, 'owner@example.com', { id: crypto.randomUUID(), title, content: `${title} 요구사항`, agentSetId: set.id }, set)
    await store.claim(workspace)
    const feature = await store.assign(workspace, run.id, { action: 'new', title, content: run.content, reason: '새 기능' })
    await store.report(workspace, run.id, report); await store.finish(workspace, run.id, 'completed')
    if (status) await store.judge(workspace, feature.id, store.read(workspace).features.find(item => item.id === feature.id)!.version, status)
    return feature.id
  }
  const loginId = await make('로그인'), searchId = await make('검색', 'verified'); await make('설정', 'needs-fix')
  const callbacks = new Map<string, AgentHostCallbacks>()
  const executor = new FeatureService(store, async (_runtime, tab, _cwd, cb) => {
    callbacks.set(tab, cb)
    cb.onEvent?.({ type: 'meta', meta: { sessionId: 'fixture-session', startedAt: '', turns: 0, busy: false, queued: [], usage: null, canLoad: true, canList: false } })
    return { close() {}, send(command) {
      if (command.type !== 'prompt') return
      const run = store.read(workspace).runs.find(item => item.tabId === tab)!
      void store.assign(workspace, run.id, {
        action: run.targetId ? 'update' : run.parentId ? 'child' : 'new', title: run.title, content: run.content, reason: '요청에 맞는 기능에 연결',
        featureId: run.targetId, version: run.targetVersion, parentId: run.parentId,
      }).then(() => cb.onEvent?.({ type: 'turn_start', startedAt: Date.now() }))
    } }
  }, async () => { throw new Error('no recovery expected') }, () => true)
  const source = `import React from '${root}/node_modules/react/index.js';import {createRoot} from '${root}/node_modules/react-dom/client.js';import {FeatureDevelopment} from '${root}/src/components/feature-development.tsx';import {I18nProvider} from '${root}/src/i18n.tsx';window.files=[];window.agents=[];createRoot(document.getElementById('root')).render(<I18nProvider><FeatureDevelopment workspace={${JSON.stringify(workspace)}} canUseGit initialState={JSON.parse(localStorage.getItem('fixture:feature-state') || 'null')} onChange={state=>{window.featureState=state;localStorage.setItem('fixture:feature-state',JSON.stringify(state))}} onClose={()=>window.closed=true} onOpenFile={path=>window.files.push(path)} onOpenAgent={run=>window.agents.push(run.tabId)}/></I18nProvider>);`
  const bundle = await build({ input: 'virtual:features.tsx', write: false, platform: 'browser', output: { format: 'iife' }, transform: { jsx: 'react-jsx', define: { 'process.env.NODE_ENV': JSON.stringify('test') } }, plugins: [{ name: 'fixture', resolveId(id) { if (id === 'virtual:features.tsx') return id; if (id.endsWith('.css')) return 'virtual:style' }, load(id) { if (id === 'virtual:features.tsx') return source; if (id === 'virtual:style') return '' } }] })
  const chunk = bundle.output.find(item => item.type === 'chunk')!
  const content = ['src/components/feature-development.tsx', 'packages/ui/src/select-field.tsx', 'packages/ui/src/dialog-frame.tsx', 'packages/ui/src/ConfirmDialog.tsx'].map(file => fs.readFileSync(path.join(root, file), 'utf8')).join('\n')
  const compiler = await compile(fs.readFileSync(path.join(root, 'src/index.css'), 'utf8'), { base: path.join(root, 'src'), onDependency() {} })
  const css = compiler.build([...new Set((source + content).match(/[A-Za-z0-9_@:/.[\]()%,-]+/g))]) + fs.readFileSync(path.join(root, 'src/components/feature-specification.css'), 'utf8')
  const app = express(); app.use(express.json())
  app.use((req, _res, next) => { req.auth = { role: 'owner', email: 'owner@example.com', mustChangePassword: false }; next() })
  app.use('/api/features', createFeatureRouter(executor))
  app.get('/api/agent-sets', (_req, res) => res.json({ sets: [set, secondSet] }))
  app.get('/api/git/commit', (_req, res) => res.json({ hash, subject: 'Add login', body: '실제 로그인 커밋', files: [{ status: 'A', path: 'login.ts' }] }))
  app.get('/app.js', (_req, res) => res.type('js').send(chunk.code))
  app.get('/', (_req, res) => res.type('html').send(`<!doctype html><html class="dark"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><div id="root" style="height:100dvh"></div><script src="/app.js"></script></html>`))
  const server = http.createServer(app); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve))
  const origin = `http://127.0.0.1:${(server.address() as { port: number }).port}`
  const browser = await chromium.launch({ executablePath: domBrowserExecutable(), chromiumSandbox: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, hasTouch: true }); page.setDefaultTimeout(6000)
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript("localStorage.setItem('mew:locale','ko')")
    await page.goto(origin)
    const row = (id: string) => page.locator(`[data-feature-id="${id}"]`)
    await row(loginId).waitFor()
    assert.equal(await page.locator('[data-feature-list] button').first().innerText(), '기능 요청')
    assert.ok((await row(loginId).boundingBox())!.height <= 32)
    assert.equal(await row(loginId).locator('[data-feature-status="implemented"]').count(), 1)
    assert.equal(await row(searchId).locator('[data-feature-status="verified"]').count(), 1)
    const dotColor = (id: string) => row(id).locator('[data-feature-status]').evaluate(el => el.ownerDocument.defaultView!.getComputedStyle(el).backgroundColor)
    assert.equal(await dotColor(loginId), 'rgb(66, 203, 179)')
    assert.equal(await dotColor(searchId), 'rgb(36, 147, 68)')
    const node = (id: string) => page.locator(`[data-feature-node="${id}"]`)
    const login = node(loginId)
    assert.equal(await page.locator('[data-feature-specification]').count(), 0)
    await page.getByRole('button', { name: '모두 펼치기', exact: true }).click()
    const section = (field: string) => login.locator(`:scope > [data-feature-specification] > ul > [data-spec-section="${field}"]`)
    for (const [field, label] of [['content', '요구사항'], ['summary', '구현 내용'], ['validation', '검증'], ['files', '관련 파일'], ['commits', '관련 커밋']]) {
      assert.equal(await section(field).locator(':scope > div').last().isHidden(), true)
      const expand = section(field).getByRole('button', { name: `${label} 펼치기`, exact: true })
      assert.equal(await expand.getAttribute('aria-expanded'), 'false')
      await expand.press('Enter')
      assert.equal(await section(field).locator(':scope > div').last().isVisible(), true)
    }
    await section('files').getByRole('button', { name: '관련 파일 접기', exact: true }).click()
    await login.getByRole('button', { name: '로그인 접기', exact: true }).click()
    await login.getByRole('button', { name: '로그인 펼치기', exact: true }).click()
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    assert.equal(await section('files').locator(':scope > div').last().isHidden(), true)
    await section('files').getByRole('button', { name: '관련 파일 펼치기', exact: true }).click()
    await section('content').getByRole('button', { name: '요구사항 편집: 로그인 요구사항', exact: true }).click()
    const draftBox = login.getByRole('textbox', { name: '요구사항', exact: true })
    await draftBox.fill('보존할 초안')
    await section('validation').getByRole('button', { name: '검증 접기', exact: true }).click()
    assert.equal(await page.getByRole('dialog').count(), 0)
    assert.equal(await draftBox.inputValue(), '보존할 초안')
    await section('validation').getByRole('button', { name: '검증 펼치기', exact: true }).click()
    await section('content').getByRole('button', { name: '요구사항 접기', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click()
    assert.equal(await draftBox.inputValue(), '보존할 초안')
    await section('content').getByRole('button', { name: '요구사항 접기', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '변경 버리기', exact: true }).click()
    assert.equal(await section('content').locator(':scope > div').last().isHidden(), true)
    await section('content').getByRole('button', { name: '요구사항 항목 추가', exact: true }).click()
    assert.equal(await draftBox.inputValue(), '')
    await draftBox.press('Escape')
    assert.equal(await login.locator('[data-spec-section="content"] [data-spec-item]').count(), 1)
    assert.equal(await page.locator('select').count(), 0)
    assert.equal(await login.getByRole('button', { name: /^상위 기능 (최상위|로그인)$/ }).count(), 0)
    assert.equal(await login.getByText('로그인', { exact: true }).count(), 1)
    await row(loginId).click()
    const titleBox = login.getByRole('textbox', { name: '제목', exact: true })
    assert.equal(await titleBox.inputValue(), '로그인')
    assert.equal(await titleBox.evaluate(el => el === el.ownerDocument.activeElement), true)
    assert.equal(await login.locator('[data-feature-header] input').count(), 1)
    assert.equal(await login.locator('[data-feature-specification]').count(), 1)
    await titleBox.press('Escape')
    assert.equal(await row(loginId).evaluate(el => el === el.ownerDocument.activeElement), true)
    await login.getByRole('button', { name: '로그인 접기', exact: true }).click()
    assert.equal(await login.locator('[data-feature-specification]').count(), 0)
    await row(loginId).click()
    assert.equal(await titleBox.inputValue(), '로그인')
    assert.equal(await login.locator('[data-feature-specification]').count(), 0)
    await titleBox.fill('버리면 안 되는 제목')
    await login.getByRole('button', { name: '로그인 펼치기', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click()
    assert.equal(await titleBox.inputValue(), '버리면 안 되는 제목')
    assert.equal(await login.locator('[data-feature-specification]').count(), 0)
    await titleBox.press('Escape')
    await login.getByRole('button', { name: '로그인 펼치기', exact: true }).click()
    const searchFeature = store.read(workspace).features.find(item => item.id === searchId)!
    const searchFile = path.join(workspace, searchFeature.documentPath!)
    fs.writeFileSync(searchFile, fs.readFileSync(searchFile, 'utf8').replace('검색 요구사항', '# 검색\n\n### 범위\n\n- **이메일**과 `코드`로 검색한다.\n  - [연결 파일](../../login.ts)을 확인한다.\n\n- 상위: [기능 지도](MOC.md).'))
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    const search = node(searchId)
    await search.getByRole('button', { name: '요구사항 펼치기', exact: true }).click()
    await search.locator('strong').filter({ hasText: '이메일' }).waitFor()
    assert.equal(await search.getByText('검색', { exact: true }).count(), 1)
    assert.equal(await search.getByText('상위:', { exact: false }).count(), 0)
    assert.equal(await search.locator('.feature-specification-preview code').innerText(), '코드')
    assert.equal(await search.locator('.feature-specification-preview ul').count(), 2)
    assert.equal(await search.locator('.feature-specification-preview').first().innerText(), '범위')
    await search.getByRole('link', { name: '연결 파일', exact: true }).click()
    assert.equal(await page.locator('[data-feature-editor]').count(), 0)
    assert.deepEqual(await page.evaluate('window.files'), ['login.ts'])
    await page.evaluate('window.files = []')
    // Clicking the rendered text itself opens its original Markdown source.
    const renderedText = await search.locator('strong').filter({ hasText: '이메일' }).boundingBox()
    await page.mouse.click(renderedText!.x + renderedText!.width / 2, renderedText!.y + renderedText!.height / 2)
    assert.equal(await search.getByRole('textbox', { name: '요구사항', exact: true }).inputValue(), '- **이메일**과 `코드`로 검색한다.')
    await search.getByRole('textbox', { name: '요구사항', exact: true }).press('Escape')

    await login.getByRole('button', { name: 'login.ts', exact: true }).click()
    assert.deepEqual(await page.evaluate('window.files'), ['login.ts'])
    const documentPath = store.read(workspace).features.find(item => item.id === loginId)!.documentPath!
    await login.getByRole('button', { name: `문서 열기: ${documentPath}`, exact: true }).click()
    assert.deepEqual(await page.evaluate('window.files'), ['login.ts', documentPath])
    await login.getByRole('button', { name: /Add login/ }).click()
    await page.getByText('실제 로그인 커밋').waitFor()
    await page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click()
    const documentFile = path.join(workspace, documentPath)
    fs.writeFileSync(documentFile, fs.readFileSync(documentFile, 'utf8').replace('로그인 요구사항', '- API timeout: 30s\n- retries: 2'))
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    await login.getByRole('button', { name: '요구사항 편집: API timeout: 30s', exact: true }).click()
    const editBox = page.getByRole('textbox', { name: '요구사항', exact: true })
    await editBox.fill('- API timeout: 60s')
    fs.writeFileSync(documentFile, fs.readFileSync(documentFile, 'utf8').replace('retries: 2', 'retries: 3'))
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    await page.getByRole('button', { name: '최신 내용 불러오기', exact: true }).waitFor()
    assert.equal(await editBox.inputValue(), '- API timeout: 60s')
    await page.getByRole('button', { name: '적용·작업 시작', exact: true }).click()
    await page.getByRole('alert').filter({ hasText: '다른 변경사항' }).waitFor()
    assert.equal(store.read(workspace).runs.length, 3)
    assert.ok(fs.readFileSync(documentFile, 'utf8').includes('retries: 3'))
    await page.getByRole('button', { name: '최신 내용 불러오기', exact: true }).click()
    await page.getByRole('button', { name: '변경 버리기', exact: true }).click()
    await login.getByRole('button', { name: '요구사항 편집: API timeout: 30s', exact: true }).click()
    await editBox.fill('- API timeout: 60s')
    await page.getByRole('combobox', { name: '에이전트셋', exact: true }).click()
    await page.getByRole('option', { name: `${secondSet.name} · codex`, exact: true }).click()
    // Network failure preserves the single-item draft and reuses its request identity.
    const attempts: string[] = []
    await page.route('**/api/features/requests', async route => {
      attempts.push(route.request().postDataJSON().id)
      if (attempts.length === 1) await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '잠시 후 다시 시도하세요' }) })
      else await route.continue()
    })
    await editBox.press('Control+Enter')
    await page.getByRole('alert').filter({ hasText: '잠시 후' }).waitFor()
    assert.equal(await editBox.inputValue(), '- API timeout: 60s')
    await page.getByRole('button', { name: '적용·작업 시작', exact: true }).click()
    await row(loginId).locator('[data-feature-status="implementing"]').waitFor()
    assert.equal(attempts[0], attempts[1])
    assert.equal(await dotColor(loginId), 'rgb(54, 135, 238)')
    const run = store.read(workspace).runs.at(-1)!
    assert.equal(run.agentSet.id, secondSet.id)
    assert.equal(run.edit?.after.content, '- API timeout: 60s\n- retries: 3')
    assert.ok(fs.readFileSync(documentFile, 'utf8').includes('- API timeout: 60s'))
    assert.equal(await page.locator('[data-feature-editor]').count(), 0)
    await login.getByRole('button', { name: '요구사항 편집: retries: 3', exact: true }).click()
    await editBox.fill('- retries: 5')
    assert.equal(await page.getByRole('button', { name: '적용·작업 시작', exact: true }).isDisabled(), true)
    await editBox.press('Escape')
    await store.report(workspace, run.id, report)
    callbacks.get(run.tabId)!.onEvent?.({ type: 'turn_end', stopReason: 'end_turn', durationMs: 10 })
    await row(loginId).locator('[data-feature-status="implemented"]').waitFor()
    await login.getByRole('button', { name: '구현 내용 편집: 로그인을 구현했습니다.', exact: true }).click()
    await page.getByRole('textbox', { name: '구현 내용', exact: true }).fill('재시도 사이에 1초 대기한다.')
    await page.getByRole('button', { name: '적용·작업 시작', exact: true }).click()
    await row(loginId).locator('[data-feature-status="implementing"]').waitFor()
    const implementationRun = store.read(workspace).runs.at(-1)!
    assert.equal(implementationRun.edit?.after.summary, '재시도 사이에 1초 대기한다.')
    assert.deepEqual(store.read(workspace).features.find(item => item.id === loginId)!.report!.files, ['login.ts'])
    await store.report(workspace, implementationRun.id, report)
    callbacks.get(implementationRun.tabId)!.onEvent?.({ type: 'turn_end', stopReason: 'end_turn', durationMs: 10 })
    await row(loginId).locator('[data-feature-status="implemented"]').waitFor()
    await login.getByRole('button', { name: '확인 완료', exact: true }).click()
    await row(loginId).locator('[data-feature-status="verified"]').waitFor()
    await login.getByRole('button', { name: '수정 필요', exact: true }).click()
    await row(loginId).locator('[data-feature-status="needs-fix"]').waitFor()
    assert.equal(await dotColor(loginId), 'rgb(223, 73, 91)')
    await login.getByRole('button', { name: '하위 기능 추가', exact: true }).click()
    const composer = page.getByRole('form', { name: '기능 요청', exact: true })
    assert.equal(await composer.getByRole('textbox').count(), 1)
    await composer.getByRole('textbox').fill('비밀번호 재설정\n복구 이메일을 보냅니다.')
    await composer.getByRole('button', { name: '맡기기', exact: true }).click()
    await login.getByRole('button', { name: '하위 기능 펼치기', exact: true }).click()
    await page.getByTitle('비밀번호 재설정', { exact: true }).waitFor()
    const childRun = store.read(workspace).runs.at(-1)!, childId = childRun.featureId!
    assert.equal(store.read(workspace).features.find(item => item.id === childId)!.parentId, loginId)
    assert.equal(await node(childId).locator('[data-feature-specification]').count(), 0)
    assert.ok((await row(childId).boundingBox())!.x > (await row(loginId).boundingBox())!.x)
    await store.report(workspace, childRun.id, report)
    callbacks.get(childRun.tabId)!.onEvent?.({ type: 'turn_end', stopReason: 'end_turn', durationMs: 20 })
    await row(childId).locator('[data-feature-status="implemented"]').waitFor()
    const childFeature = store.read(workspace).features.find(item => item.id === childId)!
    const childLink = path.relative(path.dirname(documentPath), childFeature.documentPath!).split(path.sep).join('/')
    const originalParent = fs.readFileSync(documentFile, 'utf8')
    const parentWithLinks = originalParent.replace('- retries: 3', `- retries: 3\n\n### 하위 기능\n\n- [비밀번호 재설정](${childLink})\n- [같은 기능 링크](${childLink}#요구사항)\n\n### 상세 계약\n\n- [안내](guide.md)`)
    fs.writeFileSync(documentFile, parentWithLinks)
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    const childGroup = login.locator(`[data-feature-children="${loginId}"]`)
    await childGroup.locator(`[data-feature-id="${childId}"]`).waitFor()
    await childGroup.getByRole('button', { name: '하위 기능 접기', exact: true }).click()
    assert.equal(await row(childId).count(), 0)
    await childGroup.getByRole('button', { name: '하위 기능 펼치기', exact: true }).click()
    assert.equal(await page.locator(`[data-feature-id="${childId}"]`).count(), 1)
    const parentContent = login.locator(':scope > [data-feature-specification] > ul > [data-spec-section="content"]')
    assert.equal(await parentContent.getByRole('link', { name: '비밀번호 재설정', exact: true }).count(), 0)
    assert.equal(await parentContent.getByRole('link', { name: '같은 기능 링크', exact: true }).count(), 0)
    assert.equal(await parentContent.getByRole('link', { name: '안내', exact: true }).count(), 1)
    assert.equal(await parentContent.getByText('하위 기능', { exact: true }).count(), 0)
    await login.getByRole('button', { name: '로그인 접기', exact: true }).click()
    assert.equal(await row(childId).count(), 0)
    await login.getByRole('button', { name: '로그인 펼치기', exact: true }).click()
    await childGroup.getByRole('button', { name: '하위 기능 접기', exact: true }).click()
    // A reference elsewhere in the GUI reveals the feature instead of opening its file.
    const searchChildLink = path.relative(path.dirname(searchFeature.documentPath!), childFeature.documentPath!).split(path.sep).join('/')
    fs.writeFileSync(searchFile, fs.readFileSync(searchFile, 'utf8').replace('- 상위:', `- [복구 기능](${searchChildLink})\n\n- 상위:`))
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    const openedFiles = await page.evaluate('window.files')
    await search.getByRole('link', { name: '복구 기능', exact: true }).click()
    await row(childId).waitFor()
    assert.deepEqual(await page.evaluate('window.files'), openedFiles)
    assert.equal(await page.locator('[data-feature-editor]').count(), 0)
    await node(childId).getByRole('button', { name: '비밀번호 재설정 접기', exact: true }).click()
    assert.equal(await node(childId).locator('[data-feature-specification]').count(), 0)
    await node(childId).getByRole('button', { name: '비밀번호 재설정 펼치기', exact: true }).click()
    assert.equal(fs.readFileSync(documentFile, 'utf8'), parentWithLinks)
    await page.getByRole('combobox', { name: '정렬', exact: true }).click()
    await page.getByRole('option', { name: '이름순', exact: true }).click()
    assert.equal(await page.locator('[data-feature-id]').first().getAttribute('data-feature-id'), searchId)
    await row(childId).click()
    const childTitle = node(childId).getByRole('textbox', { name: '제목', exact: true })
    await childTitle.fill('계정 복구')
    await childGroup.getByRole('button', { name: '하위 기능 접기', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click()
    assert.equal(await childTitle.inputValue(), '계정 복구')
    assert.equal(await childTitle.evaluate(el => {
      const event = new el.ownerDocument.defaultView!.KeyboardEvent('keydown', { key: 'Enter', isComposing: true, bubbles: true, cancelable: true })
      el.dispatchEvent(event)
      return event.defaultPrevented
    }), true)
    await childTitle.press('Enter')
    await page.getByTitle('계정 복구', { exact: true }).waitFor()
    const titleRun = store.read(workspace).runs.at(-1)!
    assert.equal(titleRun.edit?.after.title, '계정 복구')
    assert.equal(titleRun.edit?.after.parentId, loginId)
    assert.equal(titleRun.edit?.after.content, '비밀번호 재설정\n복구 이메일을 보냅니다.')
    await store.report(workspace, titleRun.id, report)
    callbacks.get(titleRun.tabId)!.onEvent?.({ type: 'turn_end', stopReason: 'end_turn', durationMs: 10 })
    await row(childId).locator('[data-feature-status="implemented"]').waitFor()
    // The host persists account/project state; remounting restores the supplied snapshot after fetching data.
    await search.getByRole('button', { name: '검색 접기', exact: true }).click()
    await section('files').getByRole('button', { name: '관련 파일 접기', exact: true }).click()
    await page.locator('[data-feature-list]').evaluate(el => { el.scrollTop = 240 })
    await page.waitForFunction('window.featureState.scrollTop === 240')
    const savedState = await page.evaluate('window.featureState')
    await page.reload()
    await row(loginId).waitFor()
    await page.waitForFunction('document.querySelector("[data-feature-list]").scrollTop === 240')
    assert.deepEqual(await page.evaluate('window.featureState'), savedState)
    assert.equal(await section('files').locator(':scope > div').last().isHidden(), true)
    assert.equal(await row(childId).count(), 1)
    assert.equal(await search.locator('[data-feature-specification]').count(), 0)
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    await page.waitForFunction('document.querySelector("[data-feature-list]").scrollTop === 240')
    await section('files').getByRole('button', { name: '관련 파일 펼치기', exact: true }).click()
    await search.getByRole('button', { name: '검색 펼치기', exact: true }).click()
    // The hierarchy and its properties share one scroll surface at every width.
    await page.getByRole('combobox', { name: '정렬', exact: true }).click()
    await page.getByRole('option', { name: '최초 생성순', exact: true }).click()
    await page.locator('[data-feature-list]').evaluate(el => { el.scrollTop = 0 })
    await page.screenshot({ path: '/tmp/mew-features-desktop.png' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.evaluate("document.documentElement.classList.remove('dark')")
    await section('validation').getByRole('button', { name: '검증 접기', exact: true }).tap()
    assert.equal(await section('validation').locator(':scope > div').last().isHidden(), true)
    await section('validation').getByRole('button', { name: '검증 펼치기', exact: true }).tap()
    await page.screenshot({ path: '/tmp/mew-features-mobile.png' })
    await row(childId).tap()
    assert.equal(await node(childId).getByRole('textbox', { name: '제목', exact: true }).inputValue(), '계정 복구')
    await node(childId).getByRole('textbox', { name: '제목', exact: true }).press('Escape')
    // Shared dropdowns retain keyboard/Esc and touch behavior in the narrow panel.
    const sortPicker = page.getByRole('combobox', { name: '정렬', exact: true })
    await sortPicker.focus()
    await sortPicker.press('ArrowDown')
    await page.getByRole('listbox', { name: '정렬', exact: true }).waitFor()
    await sortPicker.press('Escape')
    assert.equal(await page.getByRole('listbox').count(), 0)
    await sortPicker.tap()
    await page.getByRole('option', { name: '이름순', exact: true }).tap()
    for (const locale of ['ko', 'en', 'ja', 'zh-CN']) {
      await page.evaluate(value => { localStorage.setItem('mew:locale', value) }, locale)
      await page.reload()
      await row(loginId).waitFor()
      await page.setViewportSize({ width: 320, height: 740 })
      for (const dark of [true, false]) {
        await page.evaluate(dark ? "document.documentElement.classList.add('dark')" : "document.documentElement.classList.remove('dark')")
        assert.equal(await page.evaluate('document.documentElement.scrollWidth <= innerWidth'), true)
      }
    }
    await page.evaluate("localStorage.setItem('mew:locale','ko')")
    await page.reload()
    await row(loginId).waitFor()
    await page.setViewportSize({ width: 390, height: 844 })
    await login.getByRole('button', { name: '요구사항 편집: retries: 3', exact: true }).tap()
    await editBox.fill('- retries: 8')
    await page.getByRole('button', { name: '닫기', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click()
    assert.equal(await editBox.inputValue(), '- retries: 8')
    await editBox.press('Escape')
    await page.getByRole('button', { name: '모두 접기', exact: true }).click()
    assert.equal(await page.locator('[data-feature-specification]').count(), 0)
    await page.getByRole('button', { name: '모두 펼치기', exact: true }).click()
    await row(childId).waitFor()
    await page.getByRole('button', { name: '기능 요청', exact: true }).click()
    const requestInput = composer.getByRole('textbox', { name: '추가할 기능', exact: true })
    assert.equal(await requestInput.getAttribute('rows'), '3')
    assert.equal(await requestInput.evaluate(el => el === el.ownerDocument.activeElement), true)
    assert.equal(await composer.getByRole('button', { name: '맡기기', exact: true }).isDisabled(), true)
    await requestInput.fill('알림 설정\n이메일 알림을 선택합니다.')
    assert.equal(await page.evaluate('document.documentElement.scrollWidth <= innerWidth'), true)
    await composer.getByRole('button', { name: '맡기기', exact: true }).click()
    await page.getByTitle('알림 설정', { exact: true }).waitFor()
    const inlineRun = store.read(workspace).runs.at(-1)!
    assert.equal(inlineRun.agentSet.id, secondSet.id)
    await store.report(workspace, inlineRun.id, report)
    callbacks.get(inlineRun.tabId)!.onEvent?.({ type: 'turn_end', stopReason: 'end_turn', durationMs: 10 })
    await row(inlineRun.featureId!).locator('[data-feature-status="implemented"]').waitFor()
    setFeature('owner@example.com', 'filesWrite', false)
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    await page.getByText('읽기 전용', { exact: true }).waitFor()
    assert.equal(await login.getByRole('button', { name: '요구사항 편집: retries: 3', exact: true }).isDisabled(), true)
    assert.equal(await row(loginId).isDisabled(), true)
    await section('files').getByRole('button', { name: '관련 파일 접기', exact: true }).click()
    assert.equal(await section('files').locator(':scope > div').last().isHidden(), true)
    await section('files').getByRole('button', { name: '관련 파일 펼치기', exact: true }).click()
    await login.getByRole('button', { name: '로그인 접기', exact: true }).click()
    assert.equal(await login.locator('[data-feature-specification]').count(), 0)
    await login.getByRole('button', { name: '로그인 펼치기', exact: true }).click()
    const denied = await fetch(`${origin}/api/features/${loginId}/status`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ workspace, version: 1, status: 'verified' }) })
    assert.equal(denied.status, 403)
    const stale = await fetch(`${origin}/api/features?workspace=${encodeURIComponent('/old-project')}`); assert.equal(stale.status, 409)
    assert.deepEqual(errors, [])
  } finally {
    executor.stop(); await browser.close(); await new Promise<void>(resolve => server.close(() => resolve()))
    setWorkspaceRoot(original); fs.rmSync(temporary, { recursive: true, force: true })
  }
})
