import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import express from 'express'
import { build } from 'rolldown'
import { compile } from '@tailwindcss/node'
import { chromium, type Locator } from 'playwright-core'
import { domBrowserExecutable } from './browser-dom-executable.ts'

function tagContrast(color: string, background: string): number {
  const luminance = (value: string) => value.match(/[\d.]+/g)!.slice(0, 3).map(Number).map(number => {
    const channel = number / 255
    return channel <= .04045 ? channel / 12.92 : ((channel + .055) / 1.055) ** 2.4
  }).reduce((sum, channel, index) => sum + channel * [.2126, .7152, .0722][index], 0)
  const a = luminance(color), b = luminance(background)
  return (Math.max(a, b) + .05) / (Math.min(a, b) + .05)
}

async function assertInlineTagAlignment(row: Locator): Promise<void> {
  const metrics = await row.locator('.task-text').evaluate(el => {
    const input = el.querySelector('textarea')!, style = el.ownerDocument.defaultView!.getComputedStyle(input)
    const lineHeight = parseFloat(style.lineHeight)
    const center = input.getBoundingClientRect().top + parseFloat(style.paddingTop) + lineHeight / 2
    return [...el.querySelectorAll('.task-tag')].map(tag => { const rect = tag.getBoundingClientRect(); return { delta: Math.abs(rect.top + rect.height / 2 - center), height: rect.height, lineHeight } })
  })
  assert.ok(metrics.length > 0)
  assert.ok(metrics.every(tag => tag.delta <= 1), 'tag centers align with the first text line, including wrapped text and read-only chips')
  assert.ok(metrics.every(tag => tag.height <= tag.lineHeight), 'tag backgrounds stay within the text line height')
}

test('task panel supports continuous typing, independent objects, autosave, retry, docking and mobile', { skip: !domBrowserExecutable(), timeout: 60_000 }, async () => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'mew-task-ui-'))
  process.env.MEW_DATA_DIR = directory
  const { createTaskListRouter } = await import('./task-list-routes.ts')
  const { readTaskList } = await import('./task-list.ts')
  const { WORKSPACE_ROOT } = await import('./paths.ts')
  const root = path.resolve(import.meta.dirname, '..')
  const source = `import React,{useState} from 'react';import {createRoot} from 'react-dom/client';
import {I18nProvider} from '${root}/src/i18n.tsx';
import {TaskPanel} from '${root}/src/components/task-panel.tsx';
import {useTaskList} from '${root}/src/hooks/use-task-list.ts';
import {DockWorkspace,DockPanel} from '${root}/src/components/DockWorkspace.tsx';
import {MobileDock} from '${root}/src/components/mobile-dock.tsx';
import {useOverlayDismiss} from '@mew/ui';
localStorage.setItem('mew:locale','ko');
function Fixture(){const [open,setOpen]=useState(false),[front,setFront]=useState('editor'),[dock,setDock]=useState(null),[key,setKey]=useState(0);
const session=useTaskList(${JSON.stringify(WORKSPACE_ROOT)},'one@example.test',open);
const close=()=>{setOpen(false);setFront('editor')};useOverlayDismiss(open&&front==='tasks'?close:false,{escapePhase:'bubble'});
return <div style={{height:'100dvh',display:'flex',flexDirection:'column'}}><button onClick={()=>setKey(key+1)}>Remount panels</button>
<MobileDock active={front} openPanels={open?['editor','tasks']:['editor']} available={['editor','tasks']} hidden={false} onSelect={id=>{if(id==='tasks'){if(innerWidth>=768&&open&&front==='tasks')close();else{setOpen(true);setFront('tasks')}}else setFront('editor')}} onNavigate={()=>{}}/>
<DockWorkspace key={key} value={dock} onChange={setDock} foreground={front} apiRef={null} onEditorDrop={()=>''}>
<DockPanel id='editor' kind='editor' tabs={['editor']} mobileSelected onFocus={()=>setFront('editor')}><input aria-label='Outside'/></DockPanel>
<DockPanel id='tasks' kind='tasks' visible={open} tabs={['tasks']} mobileSelected onFocus={()=>setFront('tasks')}><TaskPanel workspace='fixture' onOpenFile={path=>{window.openedTaskFile=path}} session={session} onClose={close}/></DockPanel>
</DockWorkspace></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><I18nProvider><Fixture/></I18nProvider></React.StrictMode>);`
  const bundle = await build({ input: 'virtual:task.tsx', write: false, platform: 'browser', output: { format: 'iife' }, transform: { jsx: 'react-jsx', define: { 'process.env.NODE_ENV': JSON.stringify('test') } }, plugins: [{ name: 'task-fixture', resolveId(id) {
    if (id === 'virtual:task.tsx') return id
    if (id.endsWith('.css')) return 'virtual:style'
  }, load(id) { if (id === 'virtual:task.tsx') return source; if (id === 'virtual:style') return '' } }] })
  const chunk = bundle.output.find(item => item.type === 'chunk')!
  const ui = (await Promise.all(['src/components/task-panel.tsx', 'src/components/task-text.tsx', 'src/components/task-tag-filter.tsx', 'packages/ui/src/select-field.tsx', 'src/components/DockWorkspace.tsx', 'src/components/mobile-dock.tsx'].map(file => fs.readFile(path.join(root, file), 'utf8')))).join('\n')
  const compiler = await compile(await fs.readFile(path.join(root, 'src/index.css'), 'utf8'), { base: path.join(root, 'src'), onDependency() {} })
  const dateCss = await fs.readFile(`${root}/packages/ui/src/date-field.css`, 'utf8')
  const css = compiler.build([...new Set((source + ui).match(/[A-Za-z0-9_@!:/.[\]()%,-]+/g)), ...Array.from(dateCss.matchAll(/--color-([a-z-]+)/g), match => `bg-${match[1]}`)]) + await fs.readFile(path.join(root, 'src/components/task-panel.css'), 'utf8') + dateCss + await fs.readFile(`${root}/packages/ui/src/date-calendar.css`, 'utf8')
  const app = express()
  app.use(express.json())
  app.use((req, _res, next) => { req.auth = { role: 'owner', email: 'one@example.test', mustChangePassword: false }; next() })
  let failNext = false
  app.use('/api/task-list', (req, res, next) => { if (req.method === 'PATCH' && failNext) { failNext = false; res.status(500).json({ error: '태스크를 저장하지 못했습니다' }); return } next() }, createTaskListRouter())
  app.get('/api/tree', (_req, res) => res.json([{type:'file',name:'Reference.md',path:'docs/Reference.md'},{type:'file',name:'Reference.md',path:'nested/Reference.md'},{type:'file',name:'Space (draft).md',path:'docs/Space (draft).md'}]))
  app.get('/app.js', (_req, res) => res.type('js').send(chunk.code))
  app.get('/', (_req, res) => res.type('html').send(`<!doctype html><html class="dark"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><div id="root"></div><script src="/app.js"></script></html>`))
  const server = app.listen(0, '127.0.0.1')
  await new Promise<void>(resolve => server.once('listening', resolve))
  const address = server.address(); assert.ok(address && typeof address !== 'string')
  const base = `http://127.0.0.1:${address.port}`
  const browser = await chromium.launch({ executablePath: domBrowserExecutable(), chromiumSandbox: true })
  try {
    const one = await browser.newPage({ viewport: { width: 1100, height: 800 } })
    const two = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true })
    const errors: string[] = []
    for (const page of [one, two]) { page.setDefaultTimeout(6000); page.on('pageerror', error => errors.push(error.message)); await page.goto(base) }
    await one.locator('[data-dock-item=tasks]').click()
    const panel = one.getByRole('region', { name: '태스크', exact: true })
    const draft = panel.getByRole('textbox', { name: '새 태스크' })
    await draft.fill('계획 정리'); await draft.press('Enter')
    await draft.fill('검토하기'); await draft.press('Enter')
    let rows = panel.locator('[data-task-id]')
    assert.equal(await rows.count(), 2)
    const firstId = await rows.first().getAttribute('data-task-id')
    await draft.evaluate(el => {
      const event = el.ownerDocument.createEvent('Event')
      event.initEvent('keydown', true, true)
      Object.defineProperties(event, { key: { value: 'Enter' }, keyCode: { value: 229 }, isComposing: { value: true } })
      el.dispatchEvent(event)
    })
    assert.equal(await rows.count(), 2, 'IME confirmation does not create a separate object')
    await rows.first().getByRole('textbox', { name: '태스크 내용', exact: true }).focus(); await one.keyboard.press('Home'); await one.keyboard.press('ArrowRight'); await one.keyboard.press('ArrowRight'); await one.keyboard.press('Enter')
    assert.equal(await rows.count(), 3)
    assert.equal(await rows.first().getAttribute('data-task-id'), firstId, 'splitting retains the original object identity')
    assert.equal(await rows.nth(1).getByRole('textbox', { name: '태스크 내용', exact: true }).inputValue(), ' 정리')
    await rows.nth(1).getByRole('textbox', { name: '태스크 내용', exact: true }).evaluate(el => new Promise<void>(resolve => el.ownerDocument.defaultView!.requestAnimationFrame(() => resolve())))
    await rows.nth(1).getByRole('textbox', { name: '태스크 내용', exact: true }).fill('')
    await rows.nth(1).getByRole('textbox', { name: '태스크 내용', exact: true }).press('Backspace')
    assert.equal(await rows.count(), 2)
    await draft.evaluate((el, text) => {
      const event = el.ownerDocument.createEvent('Event')
      event.initEvent('paste', true, true)
      Object.defineProperty(event, 'clipboardData', { value: { getData: () => text } })
      el.dispatchEvent(event)
    }, '연락하기\n출시 확인')
    await rows.nth(3).waitFor()
    assert.equal(await rows.count(), 4)
    const ids = await rows.evaluateAll(elements => elements.map(el => el.getAttribute('data-task-id')))
    assert.equal(new Set(ids).size, 4, 'each line is an independent object')
    await rows.first().getByRole('checkbox').check()
    await two.locator('[data-dock-item=tasks]').tap()
    const mobile = two.getByRole('region', { name: '태스크', exact: true })
    await mobile.locator('[data-task-id]').nth(3).waitFor()
    await mobile.locator('[data-task-id]').first().locator('input:checked').waitFor()
    assert.equal(await mobile.locator('[data-task-id]').first().getByRole('checkbox').isChecked(), true)
    await mobile.locator('[data-task-id]').last().getByRole('textbox', { name: '태스크 내용', exact: true }).fill('모바일에서 수정')
    await one.waitForFunction("Array.from(document.querySelectorAll('.task-panel textarea')).some(el=>el.value==='모바일에서 수정')")
    failNext = true
    await rows.nth(1).getByRole('textbox', { name: '태스크 내용', exact: true }).fill('실패해도 유지')
    await panel.getByRole('alert').waitFor()
    assert.equal(await rows.nth(1).getByRole('textbox', { name: '태스크 내용', exact: true }).inputValue(), '실패해도 유지')
    await panel.getByRole('button', { name: '다시 저장' }).click()
    await panel.getByRole('alert').waitFor({ state: 'hidden' })
    await draft.fill('아직 작성 중')
    await one.getByRole('button', { name: 'Remount panels' }).click()
    rows = panel.locator('[data-task-id]')
    assert.equal(await rows.count(), 5, 'focus leaving a draft commits it before a panel remount')
    await one.locator('[data-dock-item=tasks]').click(); await panel.waitFor({ state: 'hidden' })
    await one.locator('[data-dock-item=tasks]').click(); await panel.waitFor()
    assert.equal(await rows.count(), 5)
    await panel.getByRole('tab', { name: '태스크' }).dblclick()
    await one.locator('[data-dock-panel=tasks][data-dock-expanded]').waitFor()
    await one.keyboard.press('Escape')
    assert.equal(await one.locator('[data-dock-expanded]').count(), 0)
    assert.equal(await panel.isVisible(), true)
    await two.evaluate("document.documentElement.classList.remove('dark')")
    assert.equal(await mobile.evaluate(el => el.scrollWidth <= el.clientWidth), true)
    await fs.mkdir('/tmp/mew-task-panel', { recursive: true })
    await one.screenshot({ path: '/tmp/mew-task-panel/desktop-dark.png' })
    await two.screenshot({ path: '/tmp/mew-task-panel/mobile-light.png' })
    await one.reload(); await one.locator('[data-dock-item=tasks]').click()
    await panel.locator('[data-task-id]').nth(4).waitFor()
    assert.equal(await panel.locator('[data-task-id]').first().getAttribute('data-task-id'), firstId)
    if (readTaskList(WORKSPACE_ROOT).length !== 5) await one.waitForResponse(async response => {
      if (!response.url().includes('/api/task-list') || !response.ok()) return false
      return (await response.json() as { tasks: unknown[] }).tasks.length === 5
    })
    assert.equal(readTaskList(WORKSPACE_ROOT).length, 5)
    const order = () => panel.locator('[data-task-id]').evaluateAll(elements => elements.map(el => el.getAttribute('data-task-id')))
    const initialOrder = await order()
    const start = (await panel.locator('[data-task-id]').first().locator('.task-check').boundingBox())!
    const end = (await panel.locator('[data-task-id]').last().boundingBox())!
    await one.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
    await one.mouse.down(); await one.mouse.move(start.x + 12, end.y + end.height + 4, { steps: 8 })
    await one.locator('[data-task-drag-preview]').waitFor()
    const liveOrder = [...initialOrder.slice(1), initialOrder[0]]
    assert.deepEqual(await order(), liveOrder, 'order updates before dropping')
    await one.waitForTimeout(400)
    assert.deepEqual(readTaskList(WORKSPACE_ROOT).map(item => item.id), initialOrder, 'live preview does not save before dropping')
    await one.screenshot({ path: '/tmp/mew-task-panel/desktop-drag.png' })
    await one.mouse.up()
    const movedOrder = [...initialOrder.slice(1), initialOrder[0]]
    assert.deepEqual(await order(), movedOrder)
    assert.equal(await panel.locator(`[data-task-id="${firstId}"]`).getByRole('checkbox').isChecked(), true, 'drag does not toggle completion')
    await mobile.locator(`[data-task-id="${firstId}"]`).waitFor()
    await mobile.locator(`[data-task-id]:nth-child(5)[data-task-id="${firstId}"]`).waitFor()
    const mobileFirst = (await mobile.locator('[data-task-id]').first().locator('.task-check').boundingBox())!
    const mobileLast = (await mobile.locator('[data-task-id]').last().boundingBox())!
    const touch = await two.context().newCDPSession(two)
    await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: mobileFirst.x + 12, y: mobileFirst.y + 14 }] })
    await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: mobileFirst.x + 12, y: mobileLast.y + mobileLast.height + 3 }] })
    await two.locator('[data-task-drag-preview]').waitFor()
    assert.equal(await mobile.locator('[data-task-id]').evaluateAll(elements => elements.some(el => el.getAnimations().some((animation: { effect?: { getTiming(): { duration: number | string } } }) => animation.effect?.getTiming().duration === 180))), true, 'live reorder uses the shared 180ms animation')
    assert.deepEqual(await mobile.locator('[data-task-id]').evaluateAll(elements => elements.map(el => el.getAttribute('data-task-id'))), [...movedOrder.slice(1), movedOrder[0]], 'touch order updates before releasing')
    await two.screenshot({ path: '/tmp/mew-task-panel/mobile-drag.png' })
    await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    const touchOrder = [...movedOrder.slice(1), movedOrder[0]]
    assert.deepEqual(await mobile.locator('[data-task-id]').evaluateAll(elements => elements.map(el => el.getAttribute('data-task-id'))), touchOrder)
    await one.waitForResponse(async response => response.url().includes('/api/task-list') && response.ok() && (await response.json() as { tasks: { id: string }[] }).tasks.map(item => item.id).join() === touchOrder.join())
    assert.deepEqual(readTaskList(WORKSPACE_ROOT).map(item => item.id), touchOrder)
    await one.reload(); await one.locator('[data-dock-item=tasks]').click()
    await panel.locator('[data-task-id]').nth(4).waitFor()
    assert.deepEqual(await order(), touchOrder, 'dragged order survives reload')
    const cancelStart = (await panel.locator('[data-task-id]').first().locator('.task-check').boundingBox())!
    const cancelTarget = (await panel.locator('[data-task-id]').nth(1).boundingBox())!
    await one.mouse.move(cancelStart.x + 12, cancelStart.y + 14); await one.mouse.down(); await one.mouse.move(cancelStart.x + 12, cancelTarget.y + cancelTarget.height / 2 + 8)
    assert.notDeepEqual(await order(), touchOrder, 'canceled drag had already changed visual order')
    await one.keyboard.press('Escape'); await one.mouse.up()
    assert.equal(await panel.isVisible(), true, 'drag Escape does not close the panel')
    assert.deepEqual(await order(), touchOrder, 'cancel leaves persisted order unchanged')
    const keyboardCheckbox = panel.locator('[data-task-id]').last().getByRole('checkbox')
    const wasChecked = await keyboardCheckbox.isChecked()
    await keyboardCheckbox.press('Alt+ArrowUp')
    const keyboardOrder = [...touchOrder.slice(0, 3), touchOrder[4], touchOrder[3]]
    assert.deepEqual(await order(), keyboardOrder)
    assert.equal(await panel.locator(`[data-task-id="${touchOrder[4]}"]`).getByRole('checkbox').isChecked(), wasChecked)
    const cancelTouch = (await mobile.locator('[data-task-id]').first().locator('.task-check').boundingBox())!
    await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: cancelTouch.x + 12, y: cancelTouch.y + 14 }] })
    await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: cancelTouch.x + 12, y: cancelTouch.y + 80 }] })
    await two.locator('[data-task-drag-preview]').waitFor()
    await touch.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
    await two.locator('[data-task-drag-preview]').waitFor({ state: 'hidden' })
    assert.equal(await panel.getByRole('button', { name: '하위 태스크 추가' }).count(), 0)
    assert.equal(await panel.locator('.task-disclosure').count(), 0)
    await draft.fill('#temporary'); await draft.press('Space')
    await panel.locator('.task-draft').getByRole('button', { name: '태그 삭제: temporary' }).click()
    assert.equal(await panel.locator('[data-task-id]').count(), 5, 'removing a draft chip does not commit or duplicate its task')
    assert.equal(await panel.locator('.task-draft .task-tag').count(), 0)
    await draft.fill('분류 작업 #abc'); await draft.press('Enter')
    assert.equal(await panel.locator('[data-task-id]').count(), 5, 'Enter first confirms the hashtag')
    assert.equal(await panel.locator('.task-draft .task-tag').innerText(), 'abc')
    await draft.press('Enter')
    const taggedId = await panel.locator('[data-task-id]').filter({ hasText: 'abc' }).getAttribute('data-task-id')
    const tagged = panel.locator(`[data-task-id="${taggedId}"]`)
    await tagged.waitFor()
    const input = tagged.getByRole('textbox', { name: '태스크 내용', exact: true })
    for (const tag of ['abcde', 'abdet', 'abdvf', 'bsas']) { await input.fill('분류 작업 #' + tag); await input.press('Space'); assert.ok((await tagged.locator('.task-tag-name').allTextContents()).includes(tag), 'Space confirms ' + tag) }
    const textBox = (await input.boundingBox())!, tagsBox = (await tagged.locator('.task-tags').boundingBox())!
    assert.ok(tagsBox.x >= textBox.x + textBox.width && tagsBox.x - textBox.x - textBox.width <= 8, 'tags sit immediately to the right of the task text')
    assert.ok(Math.abs(tagsBox.y - textBox.y) <= 4, 'tags share the text row')
    await assertInlineTagAlignment(tagged)
    const colors = await tagged.locator('.task-tag').evaluateAll(elements => elements.map(el => el.ownerDocument.defaultView!.getComputedStyle(el).backgroundColor))
    assert.ok(new Set(colors).size > 1, 'tag names receive varied colors')
    const darkPairs = await tagged.locator('.task-tag').evaluateAll(elements => elements.map(el => { const style = el.ownerDocument.defaultView!.getComputedStyle(el); return [style.color, style.backgroundColor] }))
    assert.ok(darkPairs.every(([color, background]) => tagContrast(color, background) >= 4.5), 'dark tag text meets contrast requirements')
    assert.equal(await tagged.locator('.task-tag').first().evaluate(el => el.ownerDocument.defaultView!.getComputedStyle(el).borderRadius), '9px')
    await draft.fill('#abcd'); await draft.press('Enter')
    assert.equal(await panel.locator('.task-draft .task-tag-name').innerText(), 'abcd', 'Enter creates the typed name even when a longer known tag matches')
    await panel.locator('.task-draft').getByRole('button', { name: '태그 삭제: abcd' }).click()
    await draft.fill('새 분류 #ab')
    const suggestions = one.getByRole('listbox', { name: '태그 자동완성' })
    await suggestions.waitFor()
    assert.deepEqual(await suggestions.locator('.task-tag-result').allTextContents(), ['abc', 'abcde', 'abdet', 'abdvf', 'ab'])
    await one.screenshot({ path: '/tmp/mew-task-panel/desktop-tags-dark.png' })
    await draft.press('ArrowDown'); await draft.press('ArrowDown'); await draft.press('Enter')
    assert.equal(await panel.locator('.task-draft .task-tag').innerText(), 'abcde')
    await draft.press('Enter')
    await panel.getByRole('combobox', { name: '태그 필터', exact: true }).click()
    const filterMenu = one.getByRole('listbox', { name: '태그 필터', exact: true })
    const filterTrigger = panel.getByRole('combobox', { name: '태그 필터', exact: true })
    assert.equal(await filterMenu.getAttribute('aria-multiselectable'), 'true')
    await filterMenu.getByRole('option', { name: 'bsas', exact: true }).click()
    assert.equal(await panel.locator('[data-task-id]').count(), 1)
    await filterMenu.getByRole('option', { name: 'abcde', exact: true }).click()
    assert.equal(await panel.locator('[data-task-id]').count(), 2, 'multiple tags show the union without duplicating overlapping matches')
    assert.equal(await filterMenu.getByRole('option', { selected: true }).count(), 2, 'picking tags keeps the list open')
    await filterTrigger.press('Space')
    assert.equal(await panel.locator('[data-task-id]').count(), 1, 'Space deselects the active tag')
    await filterTrigger.press('Enter')
    assert.equal(await panel.locator('[data-task-id]').count(), 2, 'Enter selects without dismissing the list')
    assert.ok((await panel.locator('.task-filter').boundingBox())!.height <= 34, 'desktop filter stays compact')
    const filterDarkPairs = await panel.locator('.task-filter-chip').evaluateAll(elements => elements.map(el => { const style = el.ownerDocument.defaultView!.getComputedStyle(el); return [style.color, style.backgroundColor] }))
    assert.ok(filterDarkPairs.every(([color, background]) => tagContrast(color, background) >= 4.5), 'dark selected filter chips meet text contrast requirements')
    await one.screenshot({ path: '/tmp/mew-task-panel/desktop-filter-dark.png' })
    await one.keyboard.press('Escape')
    assert.equal(await filterTrigger.evaluate(el => el === el.ownerDocument.activeElement), true)
    assert.equal(await panel.isVisible(), true, 'Escape closes only the filter')
    await panel.getByRole('tab', { name: '간트', exact: true }).click()
    assert.equal(await panel.locator('.task-gantt-label:not(.task-gantt-new)').count(), 2)
    await panel.locator('.task-gantt-label:not(.task-gantt-new) button').filter({ hasText: '분류 작업' }).click()
    const inspector = one.getByRole('dialog', { name: '일정 편집' })
    const inspectorText = inspector.getByRole('textbox', { name: '태스크 내용', exact: true })
    await inspectorText.fill('분류 작업 #한글'); await inspectorText.press('Space')
    await one.keyboard.press('Escape'); await inspector.waitFor({ state: 'hidden' })
    await panel.getByRole('tab', { name: '달력', exact: true }).click()
    assert.equal(await panel.locator('[data-task-id]').count(), 0, 'an undated tagged item does not appear in the calendar agenda')
    await panel.getByRole('tab', { name: '목록', exact: true }).click()
    await panel.getByRole('button', { name: '태그 필터 해제: abcde', exact: true }).press('Enter')
    assert.equal(await panel.locator('[data-task-id]').count(), 1, 'a chip removes only its filter')
    await filterTrigger.evaluate(el => new Promise<void>(resolve => el.ownerDocument.defaultView!.requestAnimationFrame(() => resolve())))
    assert.equal(await filterTrigger.evaluate(el => el === el.ownerDocument.activeElement), true, 'removing the focused chip restores filter focus')
    await tagged.locator('.task-tag-name').filter({ hasText: 'abcde' }).click()
    assert.equal(await panel.locator('[data-task-id]').count(), 2, 'task chips add a tag to the existing selection')
    await draft.fill('필터에서 추가'); await draft.press('Enter')
    const filteredNew = panel.locator('[data-task-id]').last()
    assert.deepEqual(await filteredNew.locator('.task-tag-name').allTextContents(), ['bsas', 'abcde'], 'new tasks inherit selected tags')
    await panel.getByRole('button', { name: '모든 태그 필터 해제', exact: true }).click()
    assert.equal(await panel.locator('[data-task-id]').count(), 8, 'clearing restores hidden tasks')
    await input.fill('분류 작업 #bsas'); await input.press('Space')
    assert.equal(await tagged.locator('.task-tag-name').filter({ hasText: 'bsas' }).count(), 1, 'duplicate tags stay unique')
    await input.press('Tab')
    await two.reload(); await two.locator('[data-dock-item=tasks]').tap()
    await mobile.locator(`[data-task-id="${taggedId}"]`).waitFor()
    const mobileInput = mobile.locator(`[data-task-id="${taggedId}"]`).getByRole('textbox', { name: '태스크 내용', exact: true })
    await mobileInput.fill('모바일 분류 #ab')
    assert.deepEqual(await two.getByRole('listbox', { name: '태그 자동완성' }).locator('.task-tag-result').allTextContents(), ['ab'], 'already attached tags are excluded')
    await mobileInput.fill('모바일 분류')
    await mobileInput.fill('모바일에서 여러 줄로 넘어가는 긴 태스크 내용의 첫 줄 옆에 태그를 맞춥니다')
    await mobileInput.evaluate(el => new Promise<void>(resolve => el.ownerDocument.defaultView!.requestAnimationFrame(() => resolve())))
    assert.ok((await mobileInput.boundingBox())!.height > 28, 'long mobile text wraps')
    await assertInlineTagAlignment(mobile.locator(`[data-task-id="${taggedId}"]`))
    await mobileInput.fill('모바일 분류')
    const mobileDraft = mobile.getByRole('textbox', { name: '새 태스크' })
    await mobileDraft.fill('모바일 #ab')
    await two.getByRole('listbox', { name: '태그 자동완성' }).waitFor()
    await two.setViewportSize({ width: 320, height: 844 })
    await two.locator('html').evaluate(el => el.classList.remove('dark'))
    await two.getByRole('listbox', { name: '태그 자동완성' }).evaluate(el => new Promise<void>(resolve => el.ownerDocument.defaultView!.requestAnimationFrame(() => resolve())))
    const menuBox = (await two.getByRole('listbox', { name: '태그 자동완성' }).boundingBox())!
    assert.ok(menuBox.x >= 0 && menuBox.x + menuBox.width <= 320 && menuBox.y + menuBox.height <= 844, 'tag suggestions fit the mobile viewport')
    assert.equal(await mobile.evaluate(el => el.scrollWidth <= el.clientWidth), true)
    const mobileRow = mobile.locator(`[data-task-id="${taggedId}"]`)
    const lightPairs = await mobileRow.locator('.task-tag').evaluateAll(elements => elements.map(el => { const style = el.ownerDocument.defaultView!.getComputedStyle(el); return [style.color, style.backgroundColor] }))
    assert.ok(lightPairs.every(([color, background]) => tagContrast(color, background) >= 4.5), 'light tag text meets contrast requirements')
    const mobileTextBox = (await mobileInput.boundingBox())!, mobileTagsBox = (await mobileRow.locator('.task-tags').boundingBox())!
    assert.ok(mobileTagsBox.x >= mobileTextBox.x + mobileTextBox.width && Math.abs(mobileTagsBox.y - mobileTextBox.y) <= 4, 'mobile tags stay to the right of their text')
    await assertInlineTagAlignment(mobileRow)
    await two.screenshot({ path: '/tmp/mew-task-panel/mobile-tags-light.png' })
    await two.getByRole('listbox', { name: '태그 자동완성' }).getByRole('option').first().tap()
    assert.equal(await mobile.locator('.task-draft .task-tag').innerText(), 'abc')
    const removeBox = (await mobile.locator('.task-draft .task-tag-remove').boundingBox())!
    await two.touchscreen.tap(removeBox.x + removeBox.width / 2, removeBox.y - 2)
    assert.equal(await mobile.locator('.task-draft .task-tag').count(), 0, 'touching the transparent area above the compact chip still removes it')
    await mobileDraft.fill('모바일 #abc'); await mobileDraft.press('Space')
    await mobileDraft.press('Enter')
    await two.waitForResponse(response => response.url().includes('/api/task-list') && response.request().method() === 'PATCH' && response.ok())
    const mobileFilter = mobile.getByRole('combobox', { name: '태그 필터', exact: true })
    await mobileFilter.tap()
    const mobileFilterMenu = two.getByRole('listbox', { name: '태그 필터', exact: true })
    await mobileFilterMenu.getByRole('option', { name: 'bsas', exact: true }).tap()
    await mobileFilterMenu.getByRole('option', { name: 'abcde', exact: true }).tap()
    assert.equal(await mobileFilterMenu.getByRole('option', { selected: true }).count(), 2)
    assert.equal(await mobile.locator('[data-task-id]').count(), 3)
    const filterBox = (await mobileFilterMenu.boundingBox())!
    assert.ok(filterBox.x >= 0 && filterBox.x + filterBox.width <= 320 && filterBox.y + filterBox.height <= 844, 'multi-select fits the narrow touch viewport')
    assert.ok((await mobile.locator('.task-filter').boundingBox())!.height <= 40, 'touch filter stays compact')
    assert.equal(await mobile.evaluate(el => el.scrollWidth <= el.clientWidth), true)
    const filterLightPairs = await mobile.locator('.task-filter-chip').evaluateAll(elements => elements.map(el => { const style = el.ownerDocument.defaultView!.getComputedStyle(el); return [style.color, style.backgroundColor] }))
    assert.ok(filterLightPairs.every(([color, background]) => tagContrast(color, background) >= 4.5), 'light selected filter chips meet text contrast requirements')
    await two.screenshot({ path: '/tmp/mew-task-panel/mobile-filter-light.png' })
    await two.keyboard.press('Escape')
    await mobile.getByRole('button', { name: '모든 태그 필터 해제', exact: true }).tap()
    assert.ok(readTaskList(WORKSPACE_ROOT).find(item => item.id === taggedId)?.tags?.includes('한글'))
    await one.reload(); await one.locator('[data-dock-item=tasks]').click()
    await panel.locator(`[data-task-id="${taggedId}"] .task-tag-name`).filter({ hasText: '한글' }).waitFor()
    const datedRow = mobile.locator('[data-task-id]').first()
    const datedId = await datedRow.getAttribute('data-task-id')
    await datedRow.locator('.task-date-status').click()
    const calendar = two.locator('.task-date-popover')
    await calendar.getByRole('textbox', { name: '연도' }).fill('2026')
    await calendar.getByRole('textbox', { name: '연도' }).press('Enter')
    await calendar.getByRole('textbox', { name: '월', exact: true }).fill('10')
    await calendar.getByRole('textbox', { name: '월', exact: true }).press('Enter')
    await calendar.locator('[data-date="2026-10-15"]').click()
    await Promise.all([two.waitForResponse(async response => response.url().includes('/api/task-list') && response.request().method() === 'PATCH' && response.ok() && (await response.json()).tasks.some((item: { id: string; date?: string }) => item.id === datedId && item.date === '2026-10-18')), calendar.locator('[data-date="2026-10-18"]').click()])
    await two.screenshot({ animations: 'disabled', path: '/tmp/mew-task-panel/mobile-calendar.png' })
    await two.keyboard.press('Escape')
    await two.reload(); await two.locator('[data-dock-item=tasks]').click()
    await mobile.locator(`[data-task-id="${datedId}"] .task-date-status`).click()
    await two.getByRole('textbox', { name: '종료일', exact: true }).evaluate(el => new Promise<void>(resolve => el.ownerDocument.defaultView!.requestAnimationFrame(() => resolve())))
    assert.equal(await two.getByRole('textbox', { name: '종료일', exact: true }).inputValue(), '2026-10-18')
    await two.keyboard.press('Escape')
    const readOnly = await browser.newPage()
    await readOnly.route('**/api/task-list?*', route => route.fulfill({ json: { tasks: readTaskList(WORKSPACE_ROOT), canEdit: false } }))
    await readOnly.goto(base); await readOnly.locator('[data-dock-item=tasks]').click()
    const readOnlyPanel = readOnly.getByRole('region', { name: '태스크', exact: true })
    await readOnlyPanel.locator('[data-task-id]').nth(4).waitFor()
    assert.equal(await readOnlyPanel.getByRole('textbox', { name: '새 태스크' }).count(), 0)
    assert.equal(await readOnlyPanel.getByRole('checkbox').first().isDisabled(), true)
    assert.equal(await readOnlyPanel.getByRole('textbox', { name: '태스크 내용', exact: true }).first().getAttribute('readonly'), '')
    assert.equal(await readOnlyPanel.getByRole('button', { name: '태스크 삭제' }).count(), 0)
    assert.equal(await readOnlyPanel.locator('.task-tag-remove').count(), 0)
    await assertInlineTagAlignment(readOnlyPanel.locator(`[data-task-id="${taggedId}"]`))
    for (const page of [one, two]) {
      const region = page.getByRole('region', { name: '태스크', exact: true })
      const entry = region.getByRole('textbox', { name: '새 태스크' })
      await entry.fill('@Ref')
      const suggestions = page.getByRole('listbox', { name: '파일명 검색' })
      await suggestions.waitFor()
      assert.equal(await suggestions.getByRole('option').count(), 2, 'same names retain distinct paths')
      const box = (await suggestions.boundingBox())!
      assert.ok(box.x >= 0 && box.x + box.width <= page.viewportSize()!.width)
      await page.screenshot({ path: '/tmp/mew-task-panel/' + (page === one ? 'desktop-mentions.png' : 'mobile-mentions.png') })
      await entry.press('ArrowDown')
      assert.equal(await suggestions.getByRole('option', { selected: true }).innerText(), 'nested/Reference.md')
      await entry.press('ArrowUp')
      await entry.press('Escape')
      assert.equal(await suggestions.count(), 0)
      assert.equal(await region.isVisible(), true, 'Esc dismisses mentions before the task panel')
      await entry.fill('검토 @Ref')
      await suggestions.waitFor()
      if (page === two) await suggestions.getByRole('option').first().tap()
      else await entry.press('Enter')
      assert.equal(await entry.inputValue(), '검토 [Reference](docs/Reference.md) ')
      await page.screenshot({ path: '/tmp/mew-task-panel/' + (page === one ? 'desktop-links.png' : 'mobile-links.png') })
      await entry.press('Enter')
      const link = region.getByRole('button', { name: 'Reference', exact: true }).last()
      await link.click()
      assert.equal(await link.evaluate(el => (el.ownerDocument.defaultView as unknown as { openedTaskFile: string }).openedTaskFile), 'docs/Reference.md')
      await entry.fill('@Space')
      await page.getByRole('listbox', { name: '파일명 검색' }).waitFor()
      await entry.press('Tab')
      assert.equal(await entry.inputValue(), '[Space (draft)](docs/Space%20%28draft%29.md) ')
      await entry.press('Enter')
      await region.getByRole('button', { name: 'Space (draft)', exact: true }).last().click()
      assert.equal(await entry.evaluate(el => (el.ownerDocument.defaultView as unknown as { openedTaskFile: string }).openedTaskFile), 'docs/Space (draft).md')
      await region.getByRole('status').waitFor({ state: 'hidden' })
      await page.reload(); await page.locator('[data-dock-item=tasks]').click()
      await region.getByRole('button', { name: 'Reference', exact: true }).last().waitFor()
    }
    await readOnly.reload(); await readOnly.locator('[data-dock-item=tasks]').click()
    await readOnlyPanel.getByRole('button', { name: 'Reference', exact: true }).last().click()
    assert.equal(await readOnlyPanel.evaluate(el => (el.ownerDocument.defaultView as unknown as { openedTaskFile: string }).openedTaskFile), 'docs/Reference.md')
    assert.deepEqual(errors, [])
  } finally { await browser.close(); await new Promise<void>(resolve => server.close(() => resolve())); await fs.rm(directory, { recursive: true, force: true }) }
})
