import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { parseDocument } from 'yaml'
import { taskChanges } from '../shared/task-list.ts'

test('title-based Markdown paths preserve body, properties and identity through renames, collisions and migration', async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'mew-task-md-'))
  process.env.MEW_DATA_DIR = path.join(root, 'data')
  const { readTaskList, changeTaskList, taskListFile } = await import('./task-list.ts')
  const workspace = path.join(root, 'workspace')
  const a = { id: 'a', text: '제목 #literal @literal', tags: ['작업'], done: false, startDate: '2026-10-01', date: '2026-10-06' }
  try {
    let tasks = changeTaskList(workspace, taskChanges([], [a]))
    assert.equal(tasks[0].path, 'docs/tasks/제목 #literal @literal.md')
    let file = path.join(workspace, tasks[0].path!)
    const parse = () => parseDocument(fs.readFileSync(file, 'utf8').split('---')[1]).toJS()
    assert.equal(parse().title, a.text)
    assert.equal(parse().id, undefined)
    assert.equal(readTaskList(workspace)[0].id, a.id)
    assert.deepEqual(parse().tags, a.tags)
    assert.equal(parse().startDate, a.startDate)
    assert.equal(parse().date, a.date)
    fs.appendFileSync(file, '# 본문\n\n내용을 유지합니다.\n')
    fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replace('done: false', 'done: true\ncustom: preserved # comment'))
    tasks = readTaskList(workspace)
    assert.equal(tasks[0].done, true)
    const next = [{ ...tasks[0], text: '새 제목', date: null, tags: ['새태그'] }]
    const oldFile = file
    tasks = changeTaskList(workspace, taskChanges(tasks, next))
    assert.equal(tasks[0].path, 'docs/tasks/새 제목.md')
    assert.equal(fs.existsSync(oldFile), false)
    file = path.join(workspace, tasks[0].path!)
    assert.equal(parse().title, '새 제목')
    assert.equal(parse().date, undefined)
    assert.equal(parse().custom, 'preserved')
    assert.ok(fs.readFileSync(file, 'utf8').endsWith('# 본문\n\n내용을 유지합니다.\n'))
    const renamed = path.join(workspace, 'docs/tasks/이름 변경.md')
    fs.renameSync(file, renamed)
    tasks = readTaskList(workspace)
    assert.equal(tasks[0].path, 'docs/tasks/이름 변경.md')
    const external = '---\ntitle: 직접 추가\ndone: false\n---\n'
    fs.writeFileSync(path.join(workspace, 'docs/tasks/직접 추가.md'), external)
    assert.equal(readTaskList(workspace).length, 2)
    const before = readTaskList(workspace)
    tasks = changeTaskList(workspace, taskChanges(before, before.map(task => task.id === 'a' ? { ...task, done: false } : task)))
    assert.equal(tasks[0].path, 'docs/tasks/새 제목.md', 'the title determines the filename on writable synchronization')
    assert.equal(fs.existsSync(renamed), false)
    assert.equal(fs.readFileSync(path.join(workspace, 'docs/tasks/직접 추가.md'), 'utf8'), external, 'unrelated documents remain unchanged')
    file = path.join(workspace, tasks[0].path!)
    const raw = fs.readFileSync(file, 'utf8')
    fs.writeFileSync(file, raw.replace(/^title: .*$/m, 'title: 외부 제목'))
    assert.throws(() => changeTaskList(workspace, taskChanges(before, before.filter(task => task.id !== 'a'))), /다른 창/)
    tasks = readTaskList(workspace)
    fs.mkdirSync(`${taskListFile(workspace)}.tmp-${process.pid}`)
    assert.throws(() => changeTaskList(workspace, taskChanges(tasks, [])))
    assert.deepEqual(readTaskList(workspace), tasks, 'all files roll back if metadata cannot commit')
    fs.rmdirSync(`${taskListFile(workspace)}.tmp-${process.pid}`)
    const normalized = changeTaskList(workspace, [])
    assert.equal(normalized[0].path, 'docs/tasks/외부 제목.md')
    assert.equal(fs.existsSync(file), false)
    file = path.join(workspace, normalized[0].path!)
    fs.writeFileSync(file, '---\ninvalid: [\n---\n')
    assert.throws(() => changeTaskList(workspace, []))
    assert.equal(fs.readFileSync(file, 'utf8'), '---\ninvalid: [\n---\n')
    fs.writeFileSync(file, raw)
    tasks = readTaskList(workspace)
    changeTaskList(workspace, taskChanges(tasks, tasks.filter(task => task.id !== 'a')))
    assert.equal(fs.existsSync(file), false)
    fs.unlinkSync(path.join(workspace, 'docs/tasks/직접 추가.md'))
    assert.deepEqual(readTaskList(workspace), [], 'external deletion removes the panel item')

    const collisionRoot = path.join(root, 'collisions')
    const same = [a, { ...a, id: 'b' }, { ...a, id: 'c', text: a.text.toUpperCase() }]
    let collisionTasks = changeTaskList(collisionRoot, taskChanges([], same))
    assert.deepEqual(collisionTasks.map(task => task.path), ['docs/tasks/제목 #literal @literal.md', 'docs/tasks/제목 #literal @literal (2).md', 'docs/tasks/제목 #LITERAL @LITERAL (3).md'])
    collisionTasks = changeTaskList(collisionRoot, taskChanges(collisionTasks, collisionTasks.slice(1).reverse()))
    assert.deepEqual(collisionTasks.map(task => task.path), ['docs/tasks/제목 #LITERAL @LITERAL (3).md', 'docs/tasks/제목 #literal @literal (2).md'], 'duplicate filenames remain stable after deletion and reordering')
    collisionTasks = changeTaskList(collisionRoot, taskChanges(collisionTasks, collisionTasks.map(task => ({ ...task, text: task.id === 'b' ? 'B' : 'C' }))))
    collisionTasks = changeTaskList(collisionRoot, taskChanges(collisionTasks, collisionTasks.map(task => ({ ...task, text: task.id === 'b' ? 'C' : 'B' }))))
    assert.deepEqual(collisionTasks.map(task => task.path), ['docs/tasks/B.md', 'docs/tasks/C.md'], 'filename swaps keep the correct IDs')

    const legacyRoot = path.join(root, 'legacy')
    fs.mkdirSync(path.join(legacyRoot, 'tasks'), { recursive: true })
    fs.writeFileSync(taskListFile(legacyRoot), JSON.stringify({ version: 3, order: ['old'], tags: ['보존'] }))
    const legacyRaw = '---\nid: old\ntitle: 기존 제목\ndone: true\ncustom: retained\ntags: [보존]\n---\n기존 본문\n'
    fs.writeFileSync(path.join(legacyRoot, 'tasks/old.md'), legacyRaw)
    assert.equal(readTaskList(legacyRoot)[0].path, 'tasks/old.md')
    fs.mkdirSync(`${taskListFile(legacyRoot)}.tmp-${process.pid}`)
    assert.throws(() => changeTaskList(legacyRoot, []))
    assert.equal(fs.readFileSync(path.join(legacyRoot, 'tasks/old.md'), 'utf8'), legacyRaw, 'failed migration restores the original file')
    assert.deepEqual(fs.readdirSync(path.join(legacyRoot, 'docs/tasks')), [])
    fs.rmdirSync(`${taskListFile(legacyRoot)}.tmp-${process.pid}`)
    const migrated = changeTaskList(legacyRoot, [])
    assert.equal(migrated[0].path, 'docs/tasks/기존 제목.md')
    assert.equal(fs.existsSync(path.join(legacyRoot, 'tasks/old.md')), false)
    const migratedRaw = fs.readFileSync(path.join(legacyRoot, migrated[0].path!), 'utf8')
    assert.equal(parseDocument(migratedRaw.split('---')[1]).toJS().id, undefined)
    assert.equal(parseDocument(migratedRaw.split('---')[1]).toJS().custom, 'retained')
    assert.ok(migratedRaw.endsWith('기존 본문\n'))
    assert.equal(migrated[0].id, 'old')
    assert.deepEqual(changeTaskList(legacyRoot, []), migrated, 'migration is idempotent')
    assert.equal(JSON.parse(fs.readFileSync(taskListFile(legacyRoot), 'utf8')).version, 5)

    const v4Root = path.join(root, 'version4')
    fs.mkdirSync(path.join(v4Root, 'docs/tasks'), { recursive: true })
    fs.writeFileSync(taskListFile(v4Root), JSON.stringify({ version: 4, order: ['old'], tags: ['보존'] }))
    const v4File = path.join(v4Root, 'docs/tasks/기존 제목.md')
    fs.writeFileSync(v4File, legacyRaw)
    const v4Migrated = changeTaskList(v4Root, [])
    assert.equal(v4Migrated[0].id, 'old', 'version 4 migration preserves the existing internal ID')
    assert.equal(v4Migrated[0].path, 'docs/tasks/기존 제목.md')
    assert.ok(fs.readFileSync(v4File, 'utf8').endsWith('기존 본문\n'))
    assert.equal(parseDocument(fs.readFileSync(v4File, 'utf8').split('---')[1]).toJS().id, undefined)
    const v5Metadata = JSON.parse(fs.readFileSync(taskListFile(v4Root), 'utf8'))
    assert.equal(v5Metadata.documents[0].id, 'old')
    assert.equal(v5Metadata.documents[0].path, 'docs/tasks/기존 제목.md')
    assert.deepEqual(v5Metadata.order, ['old'])
    assert.deepEqual(v5Metadata.tags, ['보존'])
    assert.equal(v5Metadata.tasks, undefined, 'sidecar metadata never copies the document contents')

    const idlessRoot = path.join(root, 'idless')
    fs.mkdirSync(path.join(idlessRoot, 'docs/tasks'), { recursive: true })
    const idlessFile = path.join(idlessRoot, 'docs/tasks/외부 문서.md')
    const body = '# 원본 본문\r\n\r\n본문 --- 구분자\r\n'
    const idlessRaw = '---\r\ntitle: 외부 문서\r\ndone: false\r\ncustom: 유지 # 사용자 주석\r\n---\r\n' + body
    fs.writeFileSync(idlessFile, idlessRaw)
    const idless = readTaskList(idlessRoot)
    assert.equal(readTaskList(idlessRoot)[0].id, idless[0].id, 'idless documents have a stable identity before metadata exists')
    const { taskDocumentsNeedMigration } = await import('./task-markdown.ts')
    assert.equal(taskDocumentsNeedMigration(idless, idlessRoot), true)
    const registered = changeTaskList(idlessRoot, [])
    assert.equal(fs.readFileSync(idlessFile, 'utf8'), idlessRaw, 'registering an idless document preserves its exact contents')
    assert.equal(taskDocumentsNeedMigration(registered, idlessRoot), false)
    fs.writeFileSync(idlessFile + '.replacement', idlessRaw.replace('done: false', 'done: true'))
    fs.renameSync(idlessFile + '.replacement', idlessFile)
    let refreshed = readTaskList(idlessRoot)
    assert.equal(refreshed[0].id, idless[0].id, 'external atomic replacement preserves identity by path')
    refreshed = changeTaskList(idlessRoot, [])
    const externallyRenamed = path.join(idlessRoot, 'docs/tasks/외부에서 변경.md')
    fs.renameSync(idlessFile, externallyRenamed)
    assert.equal(readTaskList(idlessRoot)[0].id, idless[0].id, 'external rename preserves identity by filesystem identity')
    const renamedTask = { ...refreshed[0], text: '패널 제목 변경' }
    const saved = changeTaskList(idlessRoot, taskChanges(refreshed, [renamedTask]))
    assert.equal(saved[0].id, idless[0].id)
    const savedRaw = fs.readFileSync(path.join(idlessRoot, saved[0].path!), 'utf8')
    assert.ok(savedRaw.endsWith(body), 'title changes preserve the exact original body')
    assert.equal(parseDocument(savedRaw.split('---')[1]).toJS().id, undefined)
    assert.ok(savedRaw.includes('# 사용자 주석'))
    const metadataFile = taskListFile(idlessRoot)
    const metadataRaw = fs.readFileSync(metadataFile, 'utf8')
    fs.writeFileSync(metadataFile, metadataRaw.replace('"documents":[', '"documents":[null,'))
    assert.throws(() => changeTaskList(idlessRoot, []), /Invalid task document metadata/)
    assert.equal(fs.readFileSync(path.join(idlessRoot, saved[0].path!), 'utf8'), savedRaw, 'corrupt identity metadata does not overwrite documents')
    fs.writeFileSync(metadataFile, metadataRaw)

    const inconsistentRoot = path.join(root, 'inconsistent')
    fs.mkdirSync(path.join(inconsistentRoot, 'tasks'), { recursive: true })
    fs.writeFileSync(taskListFile(inconsistentRoot), JSON.stringify({ version: 2, tasks: [a] }))
    fs.writeFileSync(path.join(inconsistentRoot, 'tasks/user.md'), external)
    assert.throws(() => changeTaskList(inconsistentRoot, []), /중복/)
    assert.equal(fs.readFileSync(path.join(inconsistentRoot, 'tasks/user.md'), 'utf8'), external, 'migration does not remove preexisting documents')
    fs.symlinkSync(taskListFile(workspace), path.join(workspace, 'docs/tasks/link.md'))
    assert.throws(() => readTaskList(workspace), /Invalid task file/)
    const linkedRoot = path.join(root, 'linked')
    fs.mkdirSync(linkedRoot)
    fs.symlinkSync(workspace, path.join(linkedRoot, 'docs'))
    assert.throws(() => changeTaskList(linkedRoot, taskChanges([], [a])), /Invalid task directory/)

    const specialRoot = path.join(root, 'special')
    const specialTasks = changeTaskList(specialRoot, taskChanges([], [
      { ...a, id: 'blank', text: '' }, { ...a, id: 'unsafe', text: '../경로/제목:*?' },
      { ...a, id: 'long', text: '아주 긴 제목 '.repeat(100) }, { ...a, id: 'reserved', text: 'CON' },
    ]))
    assert.equal(specialTasks[0].path, 'docs/tasks/제목 없음.md')
    assert.equal(specialTasks[3].path, 'docs/tasks/_CON.md')
    for (const task of specialTasks) {
      assert.equal(path.dirname(task.path!), 'docs/tasks')
      assert.ok(Buffer.byteLength(path.basename(task.path!)) <= 255)
      assert.ok(!/[<>:"/\\|?*]/.test(path.basename(task.path!)))
      assert.ok(!fs.readFileSync(path.join(specialRoot, task.path!), 'utf8').includes('id: '))
    }

    const propertyRoot = path.join(root, 'document-properties')
    let propertyTasks = changeTaskList(propertyRoot, taskChanges([], [a]))
    const propertyFile = path.join(propertyRoot, propertyTasks[0].path!)
    const propertyRaw = '---\ntitle: "제목 #literal @literal"\ndone: "false"\ntags: ""\nstartDate: "2026-10-01"\ndate: "2026-10-06"\ncustom: keep # comment\n---\n원래 본문\n'
    fs.writeFileSync(propertyFile, propertyRaw)
    propertyTasks = readTaskList(propertyRoot)
    assert.equal(propertyTasks[0].done, false)
    assert.equal(propertyTasks[0].tags, undefined)
    assert.equal(propertyTasks[0].id, a.id)
    assert.equal(propertyTasks[0].startDate, a.startDate)
    assert.equal(propertyTasks[0].date, a.date)
    assert.deepEqual(changeTaskList(propertyRoot, []), propertyTasks)
    assert.equal(fs.readFileSync(propertyFile, 'utf8'), propertyRaw, 'reading text properties does not rewrite the document')
    propertyTasks = changeTaskList(propertyRoot, taskChanges(propertyTasks, propertyTasks.map(task => ({ ...task, done: true }))))
    assert.equal(propertyTasks[0].done, true)
    assert.ok(fs.readFileSync(propertyFile, 'utf8').includes('custom: keep # comment'))
    assert.ok(fs.readFileSync(propertyFile, 'utf8').endsWith('원래 본문\n'))
    for (const [rawTags, tags] of [['"작업"', ['작업']], ["'[작업, 검증]'", ['작업', '검증']], ["'[\"작업\",\"검증\"]'", ['작업', '검증']]] as const) {
      fs.writeFileSync(propertyFile, propertyRaw.replace('done: "false"', 'done: "true"').replace('tags: ""', `tags: ${rawTags}`))
      const parsed = readTaskList(propertyRoot)
      assert.equal(parsed[0].done, true)
      assert.deepEqual(parsed[0].tags, tags)
      assert.deepEqual(changeTaskList(propertyRoot, []), parsed)
    }
    for (const invalid of ['done: "maybe"\ntags: ""', 'done: "false"\ntags: "[broken"', 'done: "false"\ntags: "[Bad Tag]"']) {
      const raw = propertyRaw.replace('done: "false"\ntags: ""', invalid)
      fs.writeFileSync(propertyFile, raw)
      assert.throws(() => changeTaskList(propertyRoot, []), /태스크 저장 파일/)
      assert.equal(fs.readFileSync(propertyFile, 'utf8'), raw, 'invalid properties still prevent destructive writes')
    }
  } finally { fs.rmSync(root, { recursive: true, force: true }) }
})
