import type { Locale } from "../i18n-locales"

const en = {
  "title": "Debugger",
  "adapter": "Adapter",
  "command": "Executable",
  "args": "Adapter arguments (JSON)",
  "transport": "Connection",
  "port": "TCP port",
  "configuration": "Launch configuration (JSON)",
  "request": "Mode",
  "save": "Save",
  "test": "Test connection",
  "install": "Install js-debug",
  "installed": "Installed",
  "notInstalled": "Not installed",
  "open": "Open debugger",
  "saved": "Saved",
  "connected": "Connection succeeded",
  "start": "Start debugging",
  "stop": "Disconnect",
  "pause": "Pause",
  "continue": "Continue",
  "next": "Step over",
  "stepIn": "Step into",
  "stepOut": "Step out",
  "close": "Close",
  "breakpoints": "Breakpoints",
  "file": "Source file",
  "line": "Line",
  "add": "Add",
  "remove": "Remove",
  "stack": "Call stack",
  "variables": "Variables",
  "watches": "Pinned watches",
  "expression": "Expression",
  "idle": "Ready",
  "starting": "Starting",
  "running": "Running",
  "stopped": "Paused",
  "terminated": "Ended",
  "error": "Error",
  "output": "Output",
  "noFrames": "Pause execution to inspect the stack and variables.",
  "noVariables": "No variables",
  "unverified": "Unverified breakpoint",
  "changed": "Changed",
  "refresh": "Refresh",
  "pin": "Pin variable",
  "emptyBreakpoints": "No breakpoints",
  "adapterArgsError": "Arguments must be a JSON array of strings.",
  "configError": "Configuration must be a JSON object.",
  "launch": "Launch",
  "attach": "Attach",
  "manage": "Debugger settings",
  "external": "Adapters run on the mew server. Install only the adapters you use.",
  "attached": "Disconnect keeps an attached process running."
}
export type DebuggerCopy = typeof en
export const debuggerCopy: Record<Locale, DebuggerCopy> = {
  en,
  "ko": {
    "title": "디버거",
    "adapter": "어댑터",
    "command": "실행 파일",
    "args": "어댑터 인수 (JSON)",
    "transport": "연결 방식",
    "port": "TCP 포트",
    "configuration": "실행 설정 (JSON)",
    "request": "모드",
    "save": "저장",
    "test": "연결 테스트",
    "install": "js-debug 설치",
    "installed": "설치됨",
    "notInstalled": "미설치",
    "open": "디버거 열기",
    "saved": "저장됨",
    "connected": "연결 성공",
    "start": "디버깅 시작",
    "stop": "연결 종료",
    "pause": "일시정지",
    "continue": "계속 실행",
    "next": "다음 줄",
    "stepIn": "함수 안으로",
    "stepOut": "함수 밖으로",
    "close": "닫기",
    "breakpoints": "브레이크포인트",
    "file": "소스 파일",
    "line": "줄",
    "add": "추가",
    "remove": "삭제",
    "stack": "호출 스택",
    "variables": "변수",
    "watches": "고정한 변수",
    "expression": "표현식",
    "idle": "준비",
    "starting": "시작 중",
    "running": "실행 중",
    "stopped": "일시정지",
    "terminated": "종료됨",
    "error": "오류",
    "output": "출력",
    "noFrames": "실행을 일시정지하면 스택과 변수를 볼 수 있습니다.",
    "noVariables": "변수 없음",
    "unverified": "확인되지 않은 브레이크포인트",
    "changed": "변경됨",
    "refresh": "새로고침",
    "pin": "변수 고정",
    "emptyBreakpoints": "브레이크포인트 없음",
    "adapterArgsError": "인수는 문자열로 된 JSON 배열이어야 합니다.",
    "configError": "실행 설정은 JSON 객체여야 합니다.",
    "launch": "실행",
    "attach": "연결",
    "manage": "디버거 설정",
    "external": "어댑터는 mew 서버에서 실행됩니다. 사용할 디버거만 설치하세요.",
    "attached": "연결한 프로세스는 연결 종료 후에도 실행됩니다."
  },
  "ja": {
    "title": "デバッガー",
    "adapter": "アダプター",
    "command": "実行ファイル",
    "args": "アダプター引数 (JSON)",
    "transport": "接続方式",
    "port": "TCP ポート",
    "configuration": "起動設定 (JSON)",
    "request": "モード",
    "save": "保存",
    "test": "接続テスト",
    "install": "js-debug をインストール",
    "installed": "インストール済み",
    "notInstalled": "未インストール",
    "open": "デバッガーを開く",
    "saved": "保存済み",
    "connected": "接続成功",
    "start": "デバッグ開始",
    "stop": "切断",
    "pause": "一時停止",
    "continue": "続行",
    "next": "ステップオーバー",
    "stepIn": "ステップイン",
    "stepOut": "ステップアウト",
    "close": "閉じる",
    "breakpoints": "ブレークポイント",
    "file": "ソースファイル",
    "line": "行",
    "add": "追加",
    "remove": "削除",
    "stack": "コールスタック",
    "variables": "変数",
    "watches": "固定した変数",
    "expression": "式",
    "idle": "準備完了",
    "starting": "起動中",
    "running": "実行中",
    "stopped": "一時停止",
    "terminated": "終了",
    "error": "エラー",
    "output": "出力",
    "noFrames": "実行を一時停止するとスタックと変数を確認できます。",
    "noVariables": "変数なし",
    "unverified": "未確認のブレークポイント",
    "changed": "変更あり",
    "refresh": "更新",
    "pin": "変数を固定",
    "emptyBreakpoints": "ブレークポイントなし",
    "adapterArgsError": "引数は文字列の JSON 配列で指定してください。",
    "configError": "起動設定は JSON オブジェクトで指定してください。",
    "launch": "起動",
    "attach": "接続",
    "manage": "デバッガー設定",
    "external": "アダプターは mew サーバーで実行されます。使用するものだけインストールしてください。",
    "attached": "切断後も接続したプロセスは実行を続けます。"
  },
  "zh-CN": {
    "title": "调试器",
    "adapter": "适配器",
    "command": "可执行文件",
    "args": "适配器参数 (JSON)",
    "transport": "连接方式",
    "port": "TCP 端口",
    "configuration": "启动配置 (JSON)",
    "request": "模式",
    "save": "保存",
    "test": "测试连接",
    "install": "安装 js-debug",
    "installed": "已安装",
    "notInstalled": "未安装",
    "open": "打开调试器",
    "saved": "已保存",
    "connected": "连接成功",
    "start": "开始调试",
    "stop": "断开",
    "pause": "暂停",
    "continue": "继续",
    "next": "单步跳过",
    "stepIn": "单步进入",
    "stepOut": "单步跳出",
    "close": "关闭",
    "breakpoints": "断点",
    "file": "源文件",
    "line": "行",
    "add": "添加",
    "remove": "删除",
    "stack": "调用堆栈",
    "variables": "变量",
    "watches": "固定变量",
    "expression": "表达式",
    "idle": "就绪",
    "starting": "启动中",
    "running": "运行中",
    "stopped": "已暂停",
    "terminated": "已结束",
    "error": "错误",
    "output": "输出",
    "noFrames": "暂停执行以查看调用堆栈和变量。",
    "noVariables": "无变量",
    "unverified": "未验证的断点",
    "changed": "已更改",
    "refresh": "刷新",
    "pin": "固定变量",
    "emptyBreakpoints": "无断点",
    "adapterArgsError": "参数必须是包含字符串的 JSON 数组。",
    "configError": "启动配置必须是 JSON 对象。",
    "launch": "启动",
    "attach": "附加",
    "manage": "调试器设置",
    "external": "适配器在 mew 服务器上运行。请只安装需要的调试器。",
    "attached": "断开后附加的进程会继续运行。"
  },
}
