import { useCallback, useEffect, useState } from 'react'
import { SelectField } from '@mew/ui'
import { Play, Pause, ArrowRight, ArrowDown, ArrowUp, Plus, Square, Download, Xmark, RefreshDouble } from 'iconoir-react'
import { useI18n } from '../i18n'
import { debuggerRequest } from '../api/debugger'
import type { BrowserAnalysisSnapshot, BrowserCapture } from '../../shared/debugger-browser'
import { debuggerCopy } from './debugger-copy'
import { DebugAction } from './debugger-controls'
import { debugInput, debuggerExtra, downloadDebugFile } from './debugger-helpers'

export function DebuggerBrowser({ root }: { root: string }) {
  const { locale } = useI18n(), c = { ...debuggerCopy[locale], ...debuggerExtra(locale) }
  const [open, setOpen] = useState(false), [tabs, setTabs] = useState<{ id: string; url: string }[]>([]), [tab, setTab] = useState(''), [session, setSession] = useState<BrowserAnalysisSnapshot | null>(null)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [kind, setKind] = useState('dom'), [value, setValue] = useState(''), [type, setType] = useState('subtree-modified')
  const [frameId, setFrameId] = useState(''), [expression, setExpression] = useState(''), [result, setResult] = useState('')
  const refresh = useCallback(async (signal?: AbortSignal) => { const status = await debuggerRequest<{ tabs: { id: string; url: string }[]; session: BrowserAnalysisSnapshot | null }>(root, '/browser', undefined, 'GET', signal); if (!signal?.aborted) { setTabs(status.tabs); setSession(status.session) } }, [root])
  useEffect(() => {
    if (!open) return
    const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>
    async function poll() { try { await refresh(controller.signal) } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : String(e)) } if (!controller.signal.aborted) timer = setTimeout(poll, 2000) }
    void poll(); return () => { controller.abort(); clearTimeout(timer) }
  }, [refresh, open])
  const firstFrame = session?.frames[0]?.id ?? ''
  useEffect(() => { setFrameId(firstFrame); setResult('') }, [session?.id, session?.revision, firstFrame])
  async function run(task: () => Promise<void>) { setBusy(true); setError(''); try { await task(); await refresh() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  const command = async (name: string, args: Record<string, unknown> = {}) => debuggerRequest<any>(root, '/browser/command', { sessionId: session?.id, command: name, arguments: args })
  const captureLabel = (kind: BrowserCapture) => kind === 'cpu' ? c.cpuProfile : kind === 'heap' ? c.heapProfile : kind === 'snapshot' ? c.heapSnapshot : c.coverage
  const exportCapture = (kind: BrowserCapture, data: unknown) => downloadDebugFile(`browser-${kind}.${kind === 'cpu' ? 'cpuprofile' : kind === 'heap' ? 'heapprofile' : kind === 'snapshot' ? 'heapsnapshot' : 'json'}`, JSON.stringify(data))
  const live = !!session && !session.closed, stopped = live && !!session.frames.length
  return <details className="border-b border-edge py-2" onToggle={e => setOpen(e.currentTarget.open)}><summary className="cursor-pointer text-xs font-medium">{c.browserAnalysis}</summary>
    {error && <div role="alert" className="break-words py-1 text-xs text-red-400">{error}</div>}
    <div className="flex min-w-0 items-end gap-1 py-1"><div className="min-w-0 flex-1"><SelectField compact label={c.browserTab} value={tab} options={tabs.map(t => ({ value: t.id, label: t.url }))} onChange={setTab} disabled={busy} /></div><DebugAction label={c.connection} disabled={busy || !tab} onClick={() => void run(async () => { await debuggerRequest(root, '/browser/connect', { tab }) })}><Play width={14} /></DebugAction><DebugAction label={c.detach} disabled={busy || !live} onClick={() => void run(async () => { await debuggerRequest(root, '/browser/close', { sessionId: session?.id }) })}><Xmark width={14} /></DebugAction></div>
    {live && <><div className="flex flex-wrap items-center gap-0.5 py-1">{(['resume', 'pause', 'next', 'stepIn', 'stepOut'] as const).map((name, i) => { const Icon = [Play, Pause, ArrowRight, ArrowDown, ArrowUp][i]; return <DebugAction key={name} label={name === 'resume' ? c.continue : c[name]} disabled={busy || (name === 'pause' ? stopped : !stopped)} onClick={() => void run(async () => { await command(name, name === 'pause' ? {} : { revision: session.revision }) })}><Icon width={14} /></DebugAction> })}<span role="status" className="min-w-0 flex-1 truncate text-xs text-ink-muted">{session.reason || session.url}</span></div>
      {(['cpu', 'heap', 'coverage'] as const).map(kind => <div key={kind} className="flex items-center text-xs"><span className="min-w-0 flex-1 truncate">{captureLabel(kind)}</span><DebugAction label={`${c.capture}: ${captureLabel(kind)}`} disabled={busy || session.capturing.includes(kind)} onClick={() => void run(async () => { await command('startCapture', { kind }) })}><Play width={14} /></DebugAction><DebugAction label={`${c.export}: ${captureLabel(kind)}`} disabled={busy || !session.capturing.includes(kind)} onClick={() => void run(async () => exportCapture(kind, await command('stopCapture', { kind })))}><Square width={13} /></DebugAction></div>)}
      <div className="flex items-center text-xs"><span className="min-w-0 flex-1 truncate">{c.heapSnapshot}</span><DebugAction label={c.heapSnapshot} disabled={busy || session.busy} onClick={() => void run(async () => exportCapture('snapshot', await command('heapSnapshot')))}><Download width={14} /></DebugAction></div>
      {session.artifacts.map(a => <button type="button" key={a.id} disabled={busy} className="flex items-center gap-1 py-1 text-xs text-accent" onClick={() => void run(async () => exportCapture(a.kind, await command('artifact', { id: a.id })))}><Download width={13} />{captureLabel(a.kind)} · {new Date(a.time).toLocaleTimeString()}</button>)}
      <details className="py-1"><summary className="cursor-pointer text-xs">{c.browserBreakpoints}</summary><form className="space-y-1 py-1" onSubmit={e => { e.preventDefault(); void run(async () => { await command('breakpoint', { kind, value, ...(kind === 'dom' ? { type } : {}) }); setValue('') }) }}><SelectField compact label={c.browserBreakpoints} value={kind} options={[{ value: 'dom', label: 'DOM' }, { value: 'event', label: 'Event' }, { value: 'xhr', label: 'XHR' }]} onChange={setKind} />{kind === 'dom' && <SelectField compact label={c.type ?? 'Type'} value={type} options={['subtree-modified', 'attribute-modified', 'node-removed'].map(value => ({ value, label: value }))} onChange={setType} />}<div className="flex gap-1"><input aria-label={kind === 'dom' ? c.domSelector : kind === 'event' ? c.eventName : c.xhrUrl} placeholder={kind === 'dom' ? c.domSelector : kind === 'event' ? c.eventName : c.xhrUrl} className={`${debugInput} flex-1`} value={value} onChange={e => setValue(e.target.value)} /><button type="submit" disabled={busy || !value} className="px-1 text-accent disabled:opacity-40" aria-label={c.name}><Plus width={14} /></button></div></form>{session.breakpoints.map(bp => <div key={bp.id} className="flex min-w-0 items-center text-xs"><span className="min-w-0 flex-1 truncate">{bp.kind}: {bp.value}</span><DebugAction label={`${c.clear}: ${bp.value}`} disabled={busy} onClick={() => void run(async () => { await command('removeBreakpoint', { id: bp.id }) })}><Xmark width={13} /></DebugAction></div>)}</details>
      {stopped && <><SelectField compact label={c.stack} value={frameId} options={session.frames.map(f => ({ value: f.id, label: `${f.name} · ${f.url}:${f.line}` }))} onChange={setFrameId} /><form className="flex gap-1 py-1" onSubmit={e => { e.preventDefault(); void run(async () => setResult(JSON.stringify(await command('evaluate', { revision: session.revision, frameId, expression }), null, 2))) }}><input aria-label={c.console} className={`${debugInput} flex-1`} value={expression} onChange={e => setExpression(e.target.value)} /><button type="submit" disabled={busy || !expression} className="px-1 text-accent" aria-label={c.execute}><Play width={14} /></button></form><DebugAction label={c.source} disabled={busy || !frameId} onClick={() => void run(async () => { const frame = session.frames.find(f => f.id === frameId); setResult((await command('source', { scriptId: frame?.scriptId })).content) })}><RefreshDouble width={14} /></DebugAction>{result && <pre className="max-h-64 overflow-auto whitespace-pre-wrap break-words text-xs">{result}</pre>}</>}
    </>}
  </details>
}
