import type { Locale } from '../i18n-locales'
const ko = {
  removed: '기능 문서가 삭제되었습니다. 편집한 내용을 복사해 보관하세요.', document: '문서 열기', title: '기능', add: '기능 요청', name: '제목', content: '요구사항', agentSet: '에이전트셋', submit: '맡기기', cancel: '취소', close: '닫기', back: '목록으로', save: '저장', saved: '저장됨', discard: '변경 버리기', unsaved: '저장하지 않은 변경사항을 버릴까요?', empty: '첫 기능을 요청해 보세요', select: '기능을 선택하세요', noSets: '에이전트 창에서 에이전트셋을 먼저 추가하세요.', load: '불러오는 중…', refresh: '새로고침', sort: '정렬', updated: '최근 변경순', nameSort: '이름순', created: '최초 생성순', parent: '상위 기능', root: '최상위', child: '하위 기능 추가', verify: '확인 완료', needsFix: '수정 필요', handoff: '에이전트에게 맡기기', implementation: '구현 내용', noReport: '아직 구현 결과가 없습니다.', validation: '검증', files: '관련 파일', commits: '관련 커밋', noFiles: '연결된 파일이 없습니다.', noCommits: '연결된 커밋이 없습니다.', history: '작업 이력', conversation: '대화 열기', stop: '중단', requests: '요청', reason: '분류 이유', retry: '다시 요청', readOnly: '읽기 전용', conflict: '다른 변경사항이 있습니다. 최신 내용을 불러오거나 변경을 보존해 주세요.', reload: '최신 내용 불러오기', expand: '펼치기', collapse: '접기', changed: '요구사항 변경', implementing: '구현 중', implemented: '구현 완료 · 확인 전', verified: '사용자 확인 완료', 'needs-fix': '수정 필요', queued: '대기 중', starting: '에이전트 연결 중', running: '진행 중', blocked: '확인 필요 · 대화 열기', cancelling: '중단 중', completed: '완료', failed: '실패', cancelled: '중단됨', noChanges: '변경 없음', commit: '커밋', source: '수정 대상', waiting: '기능을 분류하고 있습니다.', count: '개',
}
export type FeatureCopy = { [K in keyof typeof ko]: string }
export const featureCopy: Record<Locale, FeatureCopy> = {
  ko,
  en: { removed: 'The feature document was deleted. Copy your edits to keep them.', document: 'Open document', title: 'Features', add: 'Request a feature', name: 'Title', content: 'Requirements', agentSet: 'Agent set', submit: 'Assign', cancel: 'Cancel', close: 'Close', back: 'Back to list', save: 'Save', saved: 'Saved', discard: 'Discard changes', unsaved: 'Discard unsaved changes?', empty: 'Request your first feature', select: 'Select a feature', noSets: 'Add an agent set in the agent panel first.', load: 'Loading…', refresh: 'Refresh', sort: 'Sort', updated: 'Recently changed', nameSort: 'Name', created: 'Created first', parent: 'Parent feature', root: 'Top level', child: 'Add subfeature', verify: 'Mark verified', needsFix: 'Needs changes', handoff: 'Assign to agent', implementation: 'Implementation', noReport: 'No implementation report yet.', validation: 'Validation', files: 'Related files', commits: 'Related commits', noFiles: 'No linked files.', noCommits: 'No linked commits.', history: 'Work history', conversation: 'Open conversation', stop: 'Stop', requests: 'Requests', reason: 'Classification', retry: 'Request again', readOnly: 'Read only', conflict: 'There are newer changes. Reload or preserve your edits.', reload: 'Load latest', expand: 'Expand', collapse: 'Collapse', changed: 'Requirements changed', implementing: 'Implementing', implemented: 'Implemented · awaiting review', verified: 'User verified', 'needs-fix': 'Needs changes', queued: 'Queued', starting: 'Connecting agent', running: 'Running', blocked: 'Action needed · open conversation', cancelling: 'Stopping', completed: 'Completed', failed: 'Failed', cancelled: 'Stopped', noChanges: 'No changes', commit: 'Commit', source: 'Updating', waiting: 'Classifying the feature.', count: 'items' },
  'zh-CN': { removed: '功能文档已删除。请复制并保存当前编辑。', document: '打开文档', title: '功能', add: '提出功能请求', name: '标题', content: '需求', agentSet: '智能体组', submit: '分配', cancel: '取消', close: '关闭', back: '返回列表', save: '保存', saved: '已保存', discard: '放弃更改', unsaved: '放弃未保存的更改？', empty: '提出第一个功能请求', select: '选择功能', noSets: '请先在智能体面板添加智能体组。', load: '加载中…', refresh: '刷新', sort: '排序', updated: '最近修改', nameSort: '名称', created: '创建时间', parent: '上级功能', root: '顶层', child: '添加子功能', verify: '确认完成', needsFix: '需要修改', handoff: '交给智能体', implementation: '实现内容', noReport: '暂无实现报告。', validation: '验证', files: '相关文件', commits: '相关提交', noFiles: '暂无关联文件。', noCommits: '暂无关联提交。', history: '工作记录', conversation: '打开对话', stop: '停止', requests: '请求', reason: '分类理由', retry: '重新请求', readOnly: '只读', conflict: '已有新更改。请重新加载或保留当前编辑。', reload: '加载最新内容', expand: '展开', collapse: '折叠', changed: '需求已修改', implementing: '实现中', implemented: '已实现 · 待确认', verified: '用户已确认', 'needs-fix': '需要修改', queued: '排队中', starting: '正在连接智能体', running: '进行中', blocked: '需要处理 · 打开对话', cancelling: '正在停止', completed: '已完成', failed: '失败', cancelled: '已停止', noChanges: '无更改', commit: '提交', source: '修改目标', waiting: '正在分类功能。', count: '项' },
  ja: { removed: '機能文書が削除されました。編集内容をコピーして保存してください。', document: '文書を開く', title: '機能', add: '機能を依頼', name: 'タイトル', content: '要件', agentSet: 'エージェントセット', submit: '依頼', cancel: 'キャンセル', close: '閉じる', back: '一覧へ', save: '保存', saved: '保存済み', discard: '変更を破棄', unsaved: '未保存の変更を破棄しますか？', empty: '最初の機能を依頼しましょう', select: '機能を選択', noSets: '先にエージェント画面でセットを追加してください。', load: '読み込み中…', refresh: '再読み込み', sort: '並び順', updated: '更新順', nameSort: '名前順', created: '作成順', parent: '親機能', root: '最上位', child: '子機能を追加', verify: '確認完了', needsFix: '修正が必要', handoff: 'エージェントに依頼', implementation: '実装内容', noReport: '実装報告はまだありません。', validation: '検証', files: '関連ファイル', commits: '関連コミット', noFiles: '関連ファイルはありません。', noCommits: '関連コミットはありません。', history: '作業履歴', conversation: '会話を開く', stop: '中止', requests: '依頼', reason: '分類理由', retry: '再依頼', readOnly: '読み取り専用', conflict: '新しい変更があります。再読み込みするか編集を保持してください。', reload: '最新の内容を読み込む', expand: '展開', collapse: '折りたたむ', changed: '要件変更', implementing: '実装中', implemented: '実装済み · 確認待ち', verified: 'ユーザー確認済み', 'needs-fix': '修正が必要', queued: '待機中', starting: 'エージェント接続中', running: '実行中', blocked: '確認が必要 · 会話を開く', cancelling: '中止中', completed: '完了', failed: '失敗', cancelled: '中止済み', noChanges: '変更なし', commit: 'コミット', source: '修正対象', waiting: '機能を分類しています。', count: '件' },
}
