import { uiText } from '@mew/ui/i18n-core'
import {
  Accessibility,
  Activity,
  AdobeAfterEffects,
  AdobeIllustrator,
  AdobeIndesign,
  AdobeLightroom,
  AdobePhotoshop,
  AdobeXd,
  AfricanTree,
  Agile,
  AirConditioner,
  Airplane,
  Alarm,
  Album,
  AlbumOpen,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Antenna,
  AntennaSignal,
  AppWindow,
  Apple,
  AppleHalf,
  AppleMac,
  AppleSwift,
  Archery,
  Archive,
  AreaSearch,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Asterisk,
  AtSign,
  Atom,
  Attachment,
  BadgeCheck,
  Bag,
  Balcony,
  Bank,
  Barcode,
  Basketball,
  Bathroom,
  Bbq,
  BeachBag,
  Bed,
  Behance,
  Bell,
  BellNotification,
  BellOff,
  Bicycle,
  Bin,
  BinFull,
  Binocular,
  BirthdayCake,
  Bitbucket,
  BitcoinCircle,
  Bluetooth,
  Bold,
  Bonfire,
  Book,
  BookLock,
  BookStack,
  Bookmark,
  BookmarkBook,
  BowlingBall,
  Box,
  Box3dCenter,
  BoxIso,
  BoxingGlove,
  Brain,
  BreadSlice,
  Bridge3d,
  BrightStar,
  Brightness,
  Bug,
  Building,
  Bus,
  Calculator,
  Calendar,
  CalendarArrowUp,
  CalendarCheck,
  CalendarPlus,
  CalendarRotate,
  Camera,
  CandlestickChart,
  Car,
  Cart,
  CartAlt,
  Cash,
  Cell2x2,
  Cellar,
  ChatBubble,
  ChatBubbleCheck,
  ChatBubbleEmpty,
  ChatBubbleQuestion,
  ChatLines,
  Check,
  CheckCircle,
  Chocolate,
  Church,
  CinemaOld,
  Circle,
  City,
  ClipboardCheck,
  Clock,
  ClockRotateRight,
  Closet,
  Cloud,
  CloudSunny,
  Code,
  CodeBrackets,
  CodeBracketsSquare,
  Codepen,
  CoffeeCup,
  Coins,
  CollageFrame,
  Collapse,
  ColorFilter,
  ColorPicker,
  ColorWheel,
  Combine,
  Community,
  CompactDisc,
  Compass,
  Component,
  Compress,
  Computer,
  Contactless,
  ControlSlider,
  Cookie,
  Copy,
  Copyright,
  Cpu,
  CpuWarning,
  CreativeCommons,
  CreditCard,
  CreditCards,
  Crib,
  Crop,
  Crown,
  Css3,
  Cube,
  CursorPointer,
  Cutlery,
  Cycling,
  Cylinder,
  DashFlag,
  Dashboard,
  DashboardDots,
  Database,
  DatabaseBackup,
  DatabaseCheck,
  DatabaseScript,
  DatabaseSearch,
  DatabaseSettings,
  DatabaseStar,
  DatabaseStats,
  DeCompress,
  Delivery,
  DeliveryTruck,
  DesignNib,
  DesignPencil,
  Desk,
  Developer,
  Dialpad,
  DiceFive,
  DirectorChair,
  Discord,
  Dishwasher,
  Divide,
  Dna,
  Dns,
  DocMagnifyingGlass,
  DocStar,
  Dollar,
  DollarCircle,
  Donate,
  DotsGrid3x3,
  Download,
  Drag,
  Drawer,
  Dribbble,
  Drone,
  Droplet,
  EaseInOut,
  EcologyBook,
  EditPencil,
  Egg,
  ElectronicsChip,
  ElectronicsTransistor,
  Elevator,
  Emoji,
  EmojiSatisfied,
  EmptyPage,
  EthereumCircle,
  Euro,
  EvStation,
  Exclude,
  Expand,
  Eye,
  EyeClosed,
  Farm,
  FavouriteBook,
  Figma,
  FileNotFound,
  FillColor,
  Filter,
  FilterList,
  Fingerprint,
  FireFlame,
  Fish,
  Fishing,
  Flash,
  Flask,
  FloppyDisk,
  Flower,
  Fog,
  Folder,
  FolderMinus,
  FolderPlus,
  FolderSettings,
  FolderWarning,
  FootballBall,
  Frame,
  FrameAlt,
  FrameTool,
  Fridge,
  Gamepad,
  Garage,
  GasTank,
  Gift,
  Git,
  GitBranch,
  GitCherryPickCommit,
  GitCommit,
  GitCompare,
  GitFork,
  GitMerge,
  GitPullRequest,
  Github,
  GithubCircle,
  GitlabFull,
  GlassEmpty,
  GlassHalf,
  Glasses,
  Globe,
  Golf,
  GoogleDocs,
  Gps,
  GraduationCap,
  GraphDown,
  GraphUp,
  Group,
  Gym,
  HalfMoon,
  Hammer,
  Handbag,
  HardDrive,
  Hashtag,
  Hat,
  Headset,
  HeadsetHelp,
  Healthcare,
  Heart,
  HeartArrowDown,
  HeavyRain,
  HelpCircle,
  Heptagon,
  Hexagon,
  Home,
  HomeAlt,
  HomeSecure,
  HomeSimple,
  HomeUser,
  Hospital,
  HotAirBalloon,
  Hourglass,
  HouseRooms,
  Html5,
  IceCream,
  Industry,
  Infinite,
  InfoCircle,
  InputField,
  InputOutput,
  InputSearch,
  Instagram,
  Internet,
  Intersect,
  IosSettings,
  Italic,
  Jellyfish,
  Journal,
  JournalPage,
  KanbanBoard,
  Key,
  Keyframes,
  Label,
  Lamp,
  Language,
  Laptop,
  LaptopDevMode,
  Leaderboard,
  LeaderboardStar,
  Leaf,
  Learning,
  Lens,
  LensPlus,
  Lifebelt,
  LightBulb,
  Link,
  Linux,
  List,
  ListSelect,
  Lock,
  LogIn,
  LogOut,
  LotOfCash,
  Lullaby,
  MacOsWindow,
  MagicWand,
  Magnet,
  Mail,
  MailIn,
  MailOpen,
  MailOut,
  Map,
  MapPin,
  MapsArrow,
  Mastodon,
  MathBook,
  Maximize,
  Medal,
  Medal1st,
  MediaImage,
  MediaImageList,
  MediaImagePlus,
  MediaVideo,
  MediaVideoList,
  Medium,
  Megaphone,
  Menu,
  Message,
  MessageText,
  Metro,
  Microphone,
  Microscope,
  Minus,
  MinusCircle,
  Mirror,
  MobileDevMode,
  MoneySquare,
  MoonSat,
  MoreHoriz,
  Motorcycle,
  Movie,
  MultiBubble,
  MultiWindow,
  MultiplePages,
  MultiplePagesEmpty,
  MultiplePagesMinus,
  MultiplePagesPlus,
  MusicDoubleNote,
  MusicNote,
  MusicNotePlus,
  NavArrowRight,
  Navigator,
  Neighbourhood,
  Network,
  NewTab,
  NintendoSwitch,
  NoSmokingCircle,
  Notes,
  Npm,
  NpmSquare,
  NumberedListLeft,
  Octagon,
  Okrs,
  OpenBook,
  OpenNewWindow,
  OpenVpn,
  OrangeSlice,
  OrganicFood,
  Package,
  Pacman,
  Page,
  PageDown,
  PageEdit,
  PageFlip,
  PageMinus,
  PagePlus,
  PageSearch,
  PageStar,
  PageUp,
  Palette,
  Pants,
  Parking,
  PasswordCheck,
  PasswordCursor,
  PasteClipboard,
  Pause,
  PcCheck,
  PcFirewall,
  PeaceHand,
  PenTablet,
  Pentagon,
  PeopleTag,
  Percentage,
  PerspectiveView,
  PharmacyCrossCircle,
  Phone,
  PhoneIncome,
  PiggyBank,
  Pillow,
  PinSlash,
  PineTree,
  Pinterest,
  PizzaSlice,
  Planet,
  PlanetSat,
  Play,
  Playlist,
  PlaylistPlay,
  PlaystationGamepad,
  Plus,
  PlusCircle,
  Podcast,
  Pokeball,
  Post,
  Potion,
  Pound,
  Presentation,
  Printer,
  PrintingPage,
  PrivacyPolicy,
  ProfileCircle,
  Prohibition,
  Puzzle,
  QrCode,
  QuestionMark,
  Quote,
  QuoteMessage,
  Radiation,
  Rain,
  ReceiveDollars,
  Redo,
  Refresh,
  RefreshDouble,
  Repeat,
  ReportColumns,
  Reports,
  Repository,
  Restart,
  Rhombus,
  Rings,
  Rocket,
  RoundFlask,
  RoundedMirror,
  RubikCube,
  Ruler,
  Running,
  Safe,
  SafeOpen,
  Sandals,
  ScanQrCode,
  Scarf,
  Scissor,
  Screenshot,
  SeaAndSun,
  SeaWaves,
  Search,
  SecurityPass,
  Send,
  SendDiagonal,
  SendDollars,
  SendMail,
  Server,
  ServerConnection,
  Settings,
  SettingsProfiles,
  ShareAndroid,
  ShareIos,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Shirt,
  Shop,
  ShopWindow,
  ShoppingBag,
  Shuffle,
  SigmaFunction,
  SimpleCart,
  SineWave,
  Skateboarding,
  SkipNext,
  SkipPrev,
  Slash,
  SmallLamp,
  SmartphoneDevice,
  Snapchat,
  Snow,
  SnowFlake,
  Soap,
  SoccerBall,
  Sofa,
  Soil,
  Sort,
  SortDown,
  SortUp,
  SoundHigh,
  SoundLow,
  SoundOff,
  Spark,
  Sparks,
  Sphere,
  Spiral,
  Spotify,
  Square,
  SquareWave,
  Stackoverflow,
  Star,
  StarDashed,
  StatDown,
  StatUp,
  StatsReport,
  StatsUpSquare,
  Strategy,
  Stretching,
  Strikethrough,
  Stroller,
  SubmitDocument,
  Substract,
  Suggestion,
  Suitcase,
  SunLight,
  Swimming,
  Table,
  Table2Columns,
  TableRows,
  TaskList,
  Telegram,
  TennisBall,
  Terminal,
  TerminalTag,
  TestTube,
  Text,
  TextBox,
  TextSize,
  TextSquare,
  Threads,
  ThreeStars,
  ThumbsDown,
  ThumbsUp,
  Thunderstorm,
  Tiktok,
  TimeZone,
  Timer,
  Tools,
  Tournament,
  Tower,
  Trademark,
  Train,
  Tram,
  Translate,
  Trash,
  Treadmill,
  Tree,
  Trekking,
  Triangle,
  TriangleFlag,
  Trophy,
  Truck,
  Tunnel,
  Twitter,
  TwoSeaterSofa,
  Type,
  Umbrella,
  Underline,
  Undo,
  Union,
  Unity,
  Upload,
  Usb,
  User,
  UserBadgeCheck,
  UserCircle,
  UserCrown,
  UserLove,
  UserPlus,
  UserStar,
  Vegan,
  Vials,
  VideoCamera,
  VideoProjector,
  ViewGrid,
  Voice,
  VueJs,
  Walking,
  Wallet,
  WarningCircle,
  WarningTriangle,
  Wash,
  WashingMachine,
  WateringSoil,
  WebWindow,
  Weight,
  Whatsapp,
  WhiteFlag,
  Wifi,
  WifiTag,
  Wind,
  WindowTabs,
  Windows,
  Wolf,
  Wrench,
  Wristwatch,
  Www,
  Xmark,
  XmarkCircle,
  Yen,
  Yoga,
  Youtube,
  ZoomIn,
  ZoomOut,
} from 'iconoir-react'

export type IconComponent = typeof Book

/** 저장값에 붙는 접두사 — 이 접두사가 없으면 예전처럼 이모지 문자열로 본다 */
export const ICON_PREFIX = 'i:'

// 프로젝트 아이콘 목록. 키는 서버(.data/project-icons.json)에 `i:{키}`로 저장되므로 한 번 정한
// 이름은 바꾸지 않는다 — 추가만 한다. 이름을 바꾸면 이미 설정된 프로젝트의 아이콘이 사라진다.
export const ICON_GROUPS: { label: string; icons: Record<string, IconComponent> }[] = [
  {
    get label() { return uiText("문서") },
    icons: {
      book: Book,
      'open-book': OpenBook,
      'book-stack': BookStack,
      journal: Journal,
      notes: Notes,
      page: Page,
      'page-edit': PageEdit,
      bookmark: Bookmark,
      pencil: EditPencil,
      text: Text,
      folder: Folder,
      archive: Archive,
      'bookmark-book': BookmarkBook,
      'book-lock': BookLock,
      'ecology-book': EcologyBook,
      'favourite-book': FavouriteBook,
      'math-book': MathBook,
      'journal-page': JournalPage,
      'multiple-pages': MultiplePages,
      'multiple-pages-empty': MultiplePagesEmpty,
      'multiple-pages-plus': MultiplePagesPlus,
      'multiple-pages-minus': MultiplePagesMinus,
      'empty-page': EmptyPage,
      'page-flip': PageFlip,
      'page-search': PageSearch,
      'page-star': PageStar,
      'page-plus': PagePlus,
      'page-minus': PageMinus,
      'page-down': PageDown,
      'page-up': PageUp,
      'submit-document': SubmitDocument,
      'doc-magnifying-glass': DocMagnifyingGlass,
      'doc-star': DocStar,
      'printing-page': PrintingPage,
      printer: Printer,
      copy: Copy,
      'paste-clipboard': PasteClipboard,
      'clipboard-check': ClipboardCheck,
      'task-list': TaskList,
      list: List,
      'numbered-list-left': NumberedListLeft,
      'list-select': ListSelect,
      label: Label,
      quote: Quote,
      'quote-message': QuoteMessage,
      post: Post,
      presentation: Presentation,
      'report-columns': ReportColumns,
      'stats-report': StatsReport,
      table: Table,
      'table-rows': TableRows,
      'table2-columns': Table2Columns,
      'folder-plus': FolderPlus,
      'folder-minus': FolderMinus,
      'folder-settings': FolderSettings,
      'folder-warning': FolderWarning,
      attachment: Attachment,
      link: Link,
      bin: Bin,
      trash: Trash,
      'bin-full': BinFull,
      translate: Translate,
      language: Language,
      'text-box': TextBox,
      'text-size': TextSize,
      type: Type,
      hashtag: Hashtag,
      'privacy-policy': PrivacyPolicy,
      'google-docs': GoogleDocs,
      'file-not-found': FileNotFound,
      repository: Repository,
      learning: Learning,
      'graduation-cap': GraduationCap,
      suggestion: Suggestion,
      strategy: Strategy,
    },
  },
  {
    get label() { return uiText("개발") },
    icons: {
      code: Code,
      'code-brackets': CodeBrackets,
      terminal: Terminal,
      'git-fork': GitFork,
      github: Github,
      bug: Bug,
      database: Database,
      server: Server,
      cpu: Cpu,
      package: Package,
      puzzle: Puzzle,
      cloud: Cloud,
      network: Network,
      'code-brackets-square': CodeBracketsSquare,
      developer: Developer,
      git: Git,
      'git-branch': GitBranch,
      'git-commit': GitCommit,
      'git-merge': GitMerge,
      'git-pull-request': GitPullRequest,
      'git-compare': GitCompare,
      'git-cherry-pick-commit': GitCherryPickCommit,
      'github-circle': GithubCircle,
      'gitlab-full': GitlabFull,
      bitbucket: Bitbucket,
      npm: Npm,
      'npm-square': NpmSquare,
      linux: Linux,
      windows: Windows,
      'apple-mac': AppleMac,
      'apple-swift': AppleSwift,
      html5: Html5,
      css3: Css3,
      'vue-js': VueJs,
      unity: Unity,
      figma: Figma,
      codepen: Codepen,
      stackoverflow: Stackoverflow,
      'terminal-tag': TerminalTag,
      'server-connection': ServerConnection,
      dns: Dns,
      'hard-drive': HardDrive,
      'floppy-disk': FloppyDisk,
      computer: Computer,
      laptop: Laptop,
      'laptop-dev-mode': LaptopDevMode,
      'smartphone-device': SmartphoneDevice,
      'mobile-dev-mode': MobileDevMode,
      usb: Usb,
      'electronics-chip': ElectronicsChip,
      'electronics-transistor': ElectronicsTransistor,
      wifi: Wifi,
      'wifi-tag': WifiTag,
      antenna: Antenna,
      'antenna-signal': AntennaSignal,
      bluetooth: Bluetooth,
      internet: Internet,
      www: Www,
      'web-window': WebWindow,
      'app-window': AppWindow,
      'multi-window': MultiWindow,
      'mac-os-window': MacOsWindow,
      'window-tabs': WindowTabs,
      'open-new-window': OpenNewWindow,
      'new-tab': NewTab,
      dashboard: Dashboard,
      'dashboard-dots': DashboardDots,
      'kanban-board': KanbanBoard,
      component: Component,
      cell2x2: Cell2x2,
      'view-grid': ViewGrid,
      'dots-grid3x3': DotsGrid3x3,
      'sigma-function': SigmaFunction,
      infinite: Infinite,
      'qr-code': QrCode,
      'scan-qr-code': ScanQrCode,
      barcode: Barcode,
      fingerprint: Fingerprint,
      'password-check': PasswordCheck,
      'password-cursor': PasswordCursor,
      'open-vpn': OpenVpn,
      'database-backup': DatabaseBackup,
      'database-check': DatabaseCheck,
      'database-script': DatabaseScript,
      'database-search': DatabaseSearch,
      'database-stats': DatabaseStats,
      'database-settings': DatabaseSettings,
      'database-star': DatabaseStar,
      dna: Dna,
      binocular: Binocular,
      'input-field': InputField,
      'input-search': InputSearch,
      'input-output': InputOutput,
      'cpu-warning': CpuWarning,
      'pc-check': PcCheck,
      'pc-firewall': PcFirewall,
      compress: Compress,
      'de-compress': DeCompress,
    },
  },
  {
    get label() { return uiText("업무") },
    icons: {
      calendar: Calendar,
      clock: Clock,
      bell: Bell,
      mail: Mail,
      chat: ChatBubble,
      user: User,
      group: Group,
      suitcase: Suitcase,
      settings: Settings,
      tools: Tools,
      wrench: Wrench,
      hammer: Hammer,
      ruler: Ruler,
      graph: GraphUp,
      reports: Reports,
      wallet: Wallet,
      cart: Cart,
      bank: Bank,
      shield: Shield,
      lock: Lock,
      key: Key,
      'calendar-check': CalendarCheck,
      'calendar-plus': CalendarPlus,
      'calendar-arrow-up': CalendarArrowUp,
      'calendar-rotate': CalendarRotate,
      timer: Timer,
      hourglass: Hourglass,
      'time-zone': TimeZone,
      'clock-rotate-right': ClockRotateRight,
      alarm: Alarm,
      'bell-notification': BellNotification,
      'bell-off': BellOff,
      'mail-open': MailOpen,
      'mail-in': MailIn,
      'mail-out': MailOut,
      'send-mail': SendMail,
      send: Send,
      'send-diagonal': SendDiagonal,
      message: Message,
      'message-text': MessageText,
      'multi-bubble': MultiBubble,
      'chat-lines': ChatLines,
      'chat-bubble-empty': ChatBubbleEmpty,
      'chat-bubble-check': ChatBubbleCheck,
      'chat-bubble-question': ChatBubbleQuestion,
      megaphone: Megaphone,
      phone: Phone,
      'phone-income': PhoneIncome,
      headset: Headset,
      'headset-help': HeadsetHelp,
      microphone: Microphone,
      voice: Voice,
      'profile-circle': ProfileCircle,
      'user-circle': UserCircle,
      'user-plus': UserPlus,
      'user-star': UserStar,
      'user-badge-check': UserBadgeCheck,
      'user-crown': UserCrown,
      'people-tag': PeopleTag,
      community: Community,
      handbag: Handbag,
      bag: Bag,
      'shopping-bag': ShoppingBag,
      shop: Shop,
      'shop-window': ShopWindow,
      'simple-cart': SimpleCart,
      'cart-alt': CartAlt,
      'credit-card': CreditCard,
      'credit-cards': CreditCards,
      cash: Cash,
      coins: Coins,
      'lot-of-cash': LotOfCash,
      'piggy-bank': PiggyBank,
      dollar: Dollar,
      'dollar-circle': DollarCircle,
      euro: Euro,
      yen: Yen,
      pound: Pound,
      'bitcoin-circle': BitcoinCircle,
      'ethereum-circle': EthereumCircle,
      percentage: Percentage,
      donate: Donate,
      'receive-dollars': ReceiveDollars,
      'send-dollars': SendDollars,
      'money-square': MoneySquare,
      safe: Safe,
      'safe-open': SafeOpen,
      'graph-down': GraphDown,
      'stat-up': StatUp,
      'stat-down': StatDown,
      'stats-up-square': StatsUpSquare,
      'candlestick-chart': CandlestickChart,
      leaderboard: Leaderboard,
      'leaderboard-star': LeaderboardStar,
      medal: Medal,
      medal1st: Medal1st,
      okrs: Okrs,
      agile: Agile,
      tournament: Tournament,
      filter: Filter,
      'filter-list': FilterList,
      sort: Sort,
      search: Search,
      'area-search': AreaSearch,
      'ios-settings': IosSettings,
      'settings-profiles': SettingsProfiles,
      'control-slider': ControlSlider,
      dialpad: Dialpad,
      calculator: Calculator,
      desk: Desk,
      'director-chair': DirectorChair,
      building: Building,
      city: City,
      industry: Industry,
      hospital: Hospital,
      'security-pass': SecurityPass,
      'badge-check': BadgeCheck,
      'shield-check': ShieldCheck,
      'shield-alert': ShieldAlert,
      'log-in': LogIn,
      'log-out': LogOut,
      contactless: Contactless,
      delivery: Delivery,
      'delivery-truck': DeliveryTruck,
    },
  },
  {
    get label() { return uiText("창작") },
    icons: {
      camera: Camera,
      image: MediaImage,
      video: MediaVideo,
      music: MusicNote,
      palette: Palette,
      nib: DesignNib,
      sparks: Sparks,
      bulb: LightBulb,
      brain: Brain,
      scissor: Scissor,
      'design-pencil': DesignPencil,
      'magic-wand': MagicWand,
      'color-picker': ColorPicker,
      'color-wheel': ColorWheel,
      'color-filter': ColorFilter,
      'fill-color': FillColor,
      brightness: Brightness,
      lens: Lens,
      'lens-plus': LensPlus,
      crop: Crop,
      frame: Frame,
      'frame-alt': FrameAlt,
      'frame-tool': FrameTool,
      'collage-frame': CollageFrame,
      album: Album,
      'album-open': AlbumOpen,
      'media-image-list': MediaImageList,
      'media-image-plus': MediaImagePlus,
      'media-video-list': MediaVideoList,
      'video-camera': VideoCamera,
      'video-projector': VideoProjector,
      movie: Movie,
      'cinema-old': CinemaOld,
      play: Play,
      pause: Pause,
      'skip-next': SkipNext,
      'skip-prev': SkipPrev,
      playlist: Playlist,
      'playlist-play': PlaylistPlay,
      'music-double-note': MusicDoubleNote,
      'music-note-plus': MusicNotePlus,
      podcast: Podcast,
      'sound-high': SoundHigh,
      'sound-low': SoundLow,
      'sound-off': SoundOff,
      'compact-disc': CompactDisc,
      spark: Spark,
      'three-stars': ThreeStars,
      'bright-star': BrightStar,
      'star-dashed': StarDashed,
      emoji: Emoji,
      'emoji-satisfied': EmojiSatisfied,
      'pen-tablet': PenTablet,
      'adobe-photoshop': AdobePhotoshop,
      'adobe-illustrator': AdobeIllustrator,
      'adobe-xd': AdobeXd,
      'adobe-after-effects': AdobeAfterEffects,
      'adobe-indesign': AdobeIndesign,
      'adobe-lightroom': AdobeLightroom,
      dribbble: Dribbble,
      behance: Behance,
      pinterest: Pinterest,
      instagram: Instagram,
      youtube: Youtube,
      tiktok: Tiktok,
      twitter: Twitter,
      threads: Threads,
      snapchat: Snapchat,
      discord: Discord,
      telegram: Telegram,
      whatsapp: Whatsapp,
      mastodon: Mastodon,
      medium: Medium,
      spotify: Spotify,
      rings: Rings,
      spiral: Spiral,
      'sine-wave': SineWave,
      'square-wave': SquareWave,
      sphere: Sphere,
      cylinder: Cylinder,
      'box3d-center': Box3dCenter,
      'box-iso': BoxIso,
      keyframes: Keyframes,
      'ease-in-out': EaseInOut,
      bold: Bold,
      italic: Italic,
      underline: Underline,
      strikethrough: Strikethrough,
      'align-left': AlignLeft,
      'align-center': AlignCenter,
      'align-right': AlignRight,
      'align-justify': AlignJustify,
      'text-square': TextSquare,
      screenshot: Screenshot,
      drag: Drag,
      'cursor-pointer': CursorPointer,
      'perspective-view': PerspectiveView,
      mirror: Mirror,
      'rounded-mirror': RoundedMirror,
    },
  },
  {
    get label() { return uiText("생활") },
    icons: {
      home: Home,
      star: Star,
      heart: Heart,
      flash: Flash,
      cube: Cube,
      box: Box,
      compass: Compass,
      globe: Globe,
      map: Map,
      pin: MapPin,
      leaf: Leaf,
      tree: Tree,
      sun: SunLight,
      moon: HalfMoon,
      coffee: CoffeeCup,
      health: Healthcare,
      pharmacy: PharmacyCrossCircle,
      activity: Activity,
      gym: Gym,
      rocket: Rocket,
      airplane: Airplane,
      car: Car,
      bicycle: Bicycle,
      gamepad: Gamepad,
      trophy: Trophy,
      flask: Flask,
      'round-flask': RoundFlask,
      atom: Atom,
      microscope: Microscope,
      magnet: Magnet,
      'home-alt': HomeAlt,
      'home-simple': HomeSimple,
      'home-user': HomeUser,
      'home-secure': HomeSecure,
      bed: Bed,
      sofa: Sofa,
      'two-seater-sofa': TwoSeaterSofa,
      bathroom: Bathroom,
      fridge: Fridge,
      'washing-machine': WashingMachine,
      dishwasher: Dishwasher,
      'air-conditioner': AirConditioner,
      lamp: Lamp,
      'small-lamp': SmallLamp,
      closet: Closet,
      drawer: Drawer,
      garage: Garage,
      balcony: Balcony,
      elevator: Elevator,
      church: Church,
      farm: Farm,
      'pine-tree': PineTree,
      'african-tree': AfricanTree,
      flower: Flower,
      soil: Soil,
      'watering-soil': WateringSoil,
      jellyfish: Jellyfish,
      fish: Fish,
      wolf: Wolf,
      egg: Egg,
      'bread-slice': BreadSlice,
      'pizza-slice': PizzaSlice,
      'ice-cream': IceCream,
      chocolate: Chocolate,
      cookie: Cookie,
      'birthday-cake': BirthdayCake,
      cutlery: Cutlery,
      'glass-half': GlassHalf,
      'glass-empty': GlassEmpty,
      bbq: Bbq,
      apple: Apple,
      'apple-half': AppleHalf,
      'orange-slice': OrangeSlice,
      'organic-food': OrganicFood,
      vegan: Vegan,
      bonfire: Bonfire,
      'fire-flame': FireFlame,
      droplet: Droplet,
      'snow-flake': SnowFlake,
      snow: Snow,
      rain: Rain,
      'heavy-rain': HeavyRain,
      thunderstorm: Thunderstorm,
      fog: Fog,
      wind: Wind,
      umbrella: Umbrella,
      'cloud-sunny': CloudSunny,
      'sea-waves': SeaWaves,
      'sea-and-sun': SeaAndSun,
      planet: Planet,
      'planet-sat': PlanetSat,
      'moon-sat': MoonSat,
      walking: Walking,
      running: Running,
      cycling: Cycling,
      swimming: Swimming,
      yoga: Yoga,
      stretching: Stretching,
      treadmill: Treadmill,
      skateboarding: Skateboarding,
      trekking: Trekking,
      archery: Archery,
      basketball: Basketball,
      'soccer-ball': SoccerBall,
      'football-ball': FootballBall,
      'tennis-ball': TennisBall,
      'bowling-ball': BowlingBall,
      golf: Golf,
      'boxing-glove': BoxingGlove,
      fishing: Fishing,
      bus: Bus,
      train: Train,
      tram: Tram,
      metro: Metro,
      truck: Truck,
      motorcycle: Motorcycle,
      drone: Drone,
      'hot-air-balloon': HotAirBalloon,
      parking: Parking,
      'ev-station': EvStation,
      'gas-tank': GasTank,
      gps: Gps,
      'maps-arrow': MapsArrow,
      navigator: Navigator,
      'beach-bag': BeachBag,
      shirt: Shirt,
      pants: Pants,
      hat: Hat,
      glasses: Glasses,
      wristwatch: Wristwatch,
      sandals: Sandals,
      scarf: Scarf,
      crown: Crown,
      gift: Gift,
      'dice-five': DiceFive,
      'rubik-cube': RubikCube,
      pacman: Pacman,
      pokeball: Pokeball,
      'playstation-gamepad': PlaystationGamepad,
      'nintendo-switch': NintendoSwitch,
      lifebelt: Lifebelt,
      crib: Crib,
      stroller: Stroller,
      lullaby: Lullaby,
      pillow: Pillow,
      soap: Soap,
      wash: Wash,
      'no-smoking-circle': NoSmokingCircle,
      'peace-hand': PeaceHand,
      'thumbs-up': ThumbsUp,
      'thumbs-down': ThumbsDown,
      'heart-arrow-down': HeartArrowDown,
      'user-love': UserLove,
      'test-tube': TestTube,
      vials: Vials,
      radiation: Radiation,
      weight: Weight,
      accessibility: Accessibility,
      tower: Tower,
      tunnel: Tunnel,
      bridge3d: Bridge3d,
      potion: Potion,
      cellar: Cellar,
      'house-rooms': HouseRooms,
      neighbourhood: Neighbourhood,
    },
  },
  {
    get label() { return uiText("기호") },
    icons: {
      check: Check,
      'check-circle': CheckCircle,
      xmark: Xmark,
      'xmark-circle': XmarkCircle,
      plus: Plus,
      'plus-circle': PlusCircle,
      minus: Minus,
      'minus-circle': MinusCircle,
      'warning-triangle': WarningTriangle,
      'warning-circle': WarningCircle,
      'info-circle': InfoCircle,
      'help-circle': HelpCircle,
      'question-mark': QuestionMark,
      asterisk: Asterisk,
      'at-sign': AtSign,
      slash: Slash,
      circle: Circle,
      square: Square,
      triangle: Triangle,
      rhombus: Rhombus,
      pentagon: Pentagon,
      hexagon: Hexagon,
      heptagon: Heptagon,
      octagon: Octagon,
      'arrow-up': ArrowUp,
      'arrow-down': ArrowDown,
      'arrow-left': ArrowLeft,
      'arrow-right': ArrowRight,
      'arrow-up-right': ArrowUpRight,
      'arrow-down-right': ArrowDownRight,
      'nav-arrow-right': NavArrowRight,
      refresh: Refresh,
      'refresh-double': RefreshDouble,
      undo: Undo,
      redo: Redo,
      repeat: Repeat,
      shuffle: Shuffle,
      restart: Restart,
      download: Download,
      upload: Upload,
      'share-android': ShareAndroid,
      'share-ios': ShareIos,
      eye: Eye,
      'eye-closed': EyeClosed,
      'pin-slash': PinSlash,
      'triangle-flag': TriangleFlag,
      'white-flag': WhiteFlag,
      'dash-flag': DashFlag,
      copyright: Copyright,
      trademark: Trademark,
      'creative-commons': CreativeCommons,
      divide: Divide,
      'more-horiz': MoreHoriz,
      menu: Menu,
      expand: Expand,
      collapse: Collapse,
      maximize: Maximize,
      'zoom-in': ZoomIn,
      'zoom-out': ZoomOut,
      prohibition: Prohibition,
      'sort-up': SortUp,
      'sort-down': SortDown,
      combine: Combine,
      union: Union,
      intersect: Intersect,
      substract: Substract,
      exclude: Exclude,
    },
  },
]

const ICON_SET: Record<string, IconComponent> = Object.assign({}, ...ICON_GROUPS.map((g) => g.icons))

// ── 직접 넣은 SVG ────────────────────────────────────────────────────────────
// 목록에 없는 아이콘(회사 로고 등)은 SVG 코드를 그대로 값에 담는다. 검사·정리는 저장할 때
// 서버(server/svgIcon.ts)가 하고, 접두사 문자열은 그쪽과 같아야 한다(svgIcon.test.ts가 대조).
// **어느 접두사로 저장돼 있든 SVG 자체의 색은 버리고** 라인 아이콘과 같은 테마 색으로 그린다
// (ProjectIcon.tsx) — 로고마다 흰색·미색이 제각각이면 탭 줄이 얼룩덜룩해지기 때문이다.
/** 직접 넣은 SVG — 새로 저장하는 값은 전부 이것 */
export const SVG_PREFIX = 'svg:'
/** 예전에 "테마 색으로 칠하기"를 켜고 저장한 값 — 지금은 `svg:`와 똑같이 그린다 */
export const SVG_TINT_PREFIX = 'svgt:'

/** 직접 넣은 SVG 값이면 접두사를 떼어낸다 — 라인 아이콘·이모지 값이면 null */
export function splitSvgIcon(icon: string): { markup: string } | null {
  for (const prefix of [SVG_TINT_PREFIX, SVG_PREFIX]) {
    if (icon.startsWith(prefix)) return { markup: icon.slice(prefix.length) }
  }
  return null
}

export function svgIconValue(markup: string): string {
  return SVG_PREFIX + markup
}

/** <img src>·CSS 마스크에 그대로 넣을 수 있는 데이터 URL (따옴표까지 이스케이프된다) */
export function svgDataUrl(markup: string): string {
  return `data:image/svg+xml;utf8,${encodeURIComponent(markup)}`
}

/** 저장값(`i:{키}`)에 해당하는 아이콘 — 이모지이거나 모르는 키면 undefined */
export function lookupIcon(icon: string): IconComponent | undefined {
  return icon.startsWith(ICON_PREFIX) ? ICON_SET[icon.slice(ICON_PREFIX.length)] : undefined
}

/**
 * 화면에 실제로 뭔가 그려지는 값인지 — 목록에서 빠진 `i:{키}`는 아무것도 그리지 않으므로
 * (ProjectIcon이 null을 반환한다) 이름을 감춘 자리에서는 대체 표시가 필요하다.
 */
export function hasIcon(icon: string | null | undefined): boolean {
  if (!icon) return false
  const svg = splitSvgIcon(icon)
  if (svg) return svg.markup.trim().length > 0
  return icon.startsWith(ICON_PREFIX) ? ICON_SET[icon.slice(ICON_PREFIX.length)] !== undefined : true
}

export function iconValue(key: string): string {
  return ICON_PREFIX + key
}
